### ISSUE TITLE
Replace `@preconcurrency import Foundation` with scoped import

### ISSUE THREAD

**Issue by simonjbeaumont** [apple/swift-openapi-generator#114]
As discussed here: https://github.com/apple/swift-openapi-runtime/pull/22#discussion_r1261117471.

We'd like to import just the types we need from Foundation when using `@preconcurrency import` to help us track which types are lacking senbability.

**Comment by PARAIPAN9** [comment]
Hi there, I'm interested in working on this issue. Could you please assign it to me?

**Comment by czechboy0** [comment]
Hi @PARAIPAN9, sure, thanks for looking into it!

**Comment by czechboy0** [comment]
Thanks for fixing this in the runtime library, @PARAIPAN9!

Before we close this issue, it'd be good to also address this in the generator, specifically in the generated files, for example https://github.com/apple/swift-openapi-generator/blob/ed61e741d262a894bc1303d2e92506368b3da394/Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Types.swift#L4

**Comment by PARAIPAN9** [comment]
Sure thing
