### ISSUE TITLE
Some HTTP status error codes throw OpenAPIRuntime.ClientError, others don't 

### ISSUE THREAD

**Issue by abacusgiesinger** [apple/swift-openapi-generator#125]
I generate my API client with this tool and use the default runtime and transport packages. I execute the request with `try await` inside a `do catch` block. I have observed behavior that makes little sense to me in terms of error handling.

After the request is executed there are two possible options:
1.  I continue with the response, because no error was thrown
2. The catch block gets triggered, because an OpenAPIRuntime.ClientError is thrown

So far so good. The part that is confusing me, is that not all errors land in the catch block.

In my case the options for the response status code are: 200, 201, 400, 401, 422, and 500. I would expect 200 and 201 to continue as normal and every status code >= 400 to land in the catch block.

However, the error with the status code 422 lands in the response block. I suspect this is the case, because in my case the response type for a 422 is the same as it is for a 200 and different for the other error cases. 

But just because the response type is the same as in the success case, doesn't mean a 422 isn't an error case that I want to handle in the catch block. 

Is my assumption about the reason for this difference correct? And does it make sense for a 422 to not land in the catch block?

**Comment by czechboy0** [comment]
Hi @abacusgiesinger,

a call to a generated client's method only throws an error when:
- the underlying transport or any middleware throws an error
- the request cannot be serialized, or the response cannot be deserialized (for example, a require property is missing in the JSON payload)

In other words, an error is only thrown, if the generated code can't perform an HTTP operation as documented in the OpenAPI document.

The generated code _doesn't_ thrown an error for any individual HTTP status codes, as what _success_ and _failure_ means is completely in the application logic's layer. So for example, if you get back 401, and the response of the 401 body followed the OpenAPI document's description of the schema, you will get the response value, without an error being thrown.

As a client, it is your responsibility to unwrap the response enum (aka `Output`) to find out which status code was returned, and it is up to you to decide which HTTP status codes mean success versus failure to you, and how to react to it (abort, retry, continue with a default value, etc).

For details, check out the step-by-step [client tutorial](https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.4/tutorials/swift-openapi-generator/clientswiftpm), or check out the [WWDC talk](https://developer.apple.com/wwdc23/10171). 

If this answers your question, please close the issue :pray:

**Comment by abacusgiesinger** [comment]
This makes a lot more sense. 

I have checked our YAML again and it turns out the error type had a required item that was missing from the response and I failed to realize this.

Apologies for wasting your time!

Thanks for your help, the client works as expected now that I have corrected my mistake.
