### ISSUE TITLE
Emit JSON path reference in comments for all generated types

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#13]
This already works for many types and properties, but not for all.

We should ensure that all content from the OpenAPI doc generated in Swift includes a comment linking it back to its original JSON path in the OpenAPI doc.

For example:

```swift
/// - Remark: Generated from `#/paths/\/pets\/{petId}/patch/requestBody/content/application\/json/schema`.
```

**Comment by takeshi-1000** [comment]
Hi @czechboy0, 
I will try to check this. Is this issue related to #25 ? I haven't looked into the details yet, but would like to know if #25 is blocking this issue for example.

**Comment by czechboy0** [comment]
Nope, this is purely about emitting the special comments that inform the adopter where the symbol came from within the OpenAPI doc.

**Comment by takeshi-1000** [comment]
OK thanks. 🙏
