### ISSUE TITLE
Multiple OpenAPI spec files

### ISSUE THREAD

**Issue by daliad007** [apple/swift-openapi-generator#132]
Hello, 

Would like to know if it's currently possible to use the package with more than one specification file. This is needed in our project as we'd look at consuming multiple services.

Thank you!

**Comment by czechboy0** [comment]
Hi @daliad007, yes you can put one OpenAPI document into each target, so it's best to follow [this strategy](https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.5/documentation/swift-openapi-generator/api-stability-of-generated-code#Create-a-curated-client-library-package), and then import the targets with generated code into your target that uses the generated code.

**Comment by daliad007** [comment]
That makes sense. Looking at the doc, it seems it's also possible to generate the client in your own Swift package. So, in this case there could be multiple packages consuming each its own service. The packages would then be imported into our target.

**Comment by czechboy0** [comment]
Exactly. You don't need a whole package for each, you can have a separate target for each document, all within the same package. But the point stands, you should be able to talk to any number of services from your client using the generated code.

**Comment by sureshjoshi** [comment]
Is there anything that prevents multiple OpenAPI specs from running in a single target? Like, let's say we generate them in separate targets - but then have some sort of copy command to have them run in a single target. I believe they're namespaced out, other than a handful of common files?

I'm wondering because I've been having a bit of a nightmare of a time creating a binary framework package since Xcode 14.3 when I have multiple targets, but it appears to work fine with a single target. 

Trying to workaround this problem in the short term until I can figure out the long term solution.

**Comment by czechboy0** [comment]
Are you using the generated types in the public API of the binary framework? If you avoid that, and use `@_implementationOnly import` when importing the modules with the generated code, it should all work well even with many modules imported from the module of the framework.

**Comment by sureshjoshi** [comment]
@czechboy0 Thanks! That was very helpful information - there appeared to be something else wrong in 14.3.1 that magically disappeared in 15.0 (didn't even change my code/scripts 🤷🏽 ).

For anyone checking this out later, you'll probably want to `@_implementationOnly` the OpenAPI libs, as well as your generated target (if not used in the public interface).

```swift
@_implementationOnly import MyGeneratedAPI
import Foundation
@_implementationOnly import OpenAPIRuntime
@_implementationOnly import OpenAPIURLSession
```

**Comment by czechboy0** [comment]
@sureshjoshi, yes, but only if you're building with library evolution mode enabled.

**Comment by hrabkin** [comment]
@czechboy0 I used the approach and created a separate package but now in my product's target I face an issue with internal access of generated Components.Schema from the library. What the reason to generate internal accessible model if I can't use it inside my product? Is there way I can get at least raw format and decode it into a product's model?

**Comment by hrabkin** [comment]
Nevermind, I found his [thread](https://github.com/apple/swift-openapi-generator/issues/533) which resolved my issue
