### ISSUE TITLE
Add support for "index" document name (index.yaml and index.yml)

### ISSUE THREAD

**Issue by andrewse02** [apple/swift-openapi-generator#134]
Although OpenAPI [recommends](https://swagger.io/specification/#:~:text=It%20is%20RECOMMENDED%20that%20the%20root%20OpenAPI%20document%20be%20named%3A%20openapi.json%20or%20openapi.yaml.) "openapi" for the name of the document, it is common for projects to use the name "index".

For some, this may be flexible. However, there are cases where the name of this document can't be changed without a lot of effort. An example would be if all specs are stored in a particular repository, and said repository is referenced in many other repositories as a submodule. A lot of work could be required to find and replace all references to this file name.

**Comment by czechboy0** [comment]
You can use a symlink, and generate code into a dedicated target.

**Comment by simonjbeaumont** [comment]
@andrewse02 I'm not sure I fully understood the use case you're referring to. 

> However, there are cases where the name of this document can't be changed without a lot of effort. An example would be if all specs are stored in a particular repository, and said repository is referenced in many other repositories as a submodule. A lot of work could be required to find and replace all references to this file name.

To adopt Swift OpenAPI Generator in a project, it is already necessary to create a target with both the OpenAPI document and plugin config file. So there will be some need to copy or symlink the document you desire for each target from this repo of many specs, so presumably the symlink approach @czechboy0 suggests will suffice?

**Comment by andrewse02** [comment]
Oops, totally forgot about symlinks. Must not have been all there there when I wrote this 😅

**Comment by czechboy0** [comment]
@andrewse02 try it out, and if it solves the problem, feel free to close this issue 🙂

**Comment by czechboy0** [comment]
The workaround above should work, feel free to reopen if it doesn't.
