### ISSUE TITLE
Deprecation warnings not emitted when calling operations that are deprecated 

### ISSUE THREAD

**Issue by PadraigK** [apple/swift-openapi-generator#149]
When an operation is marked deprecated, the generated gives the APIProtocol definition an availability annotation marking it as deprecated. However the method on the `Client` object which implements the protocol is not given an annotation. When it is called, no warning is emitted. It's not clear to me if this is an Xcode/Swift bug, or expected behaviour.

```swift
let client = Client(
               serverURL: URL(string:"https://api.something.com")!,
               configuration: .init(),
               transport: URLSessionTransport(),
               middlewares: []
)

let erasedClient : some APIProtocol = client

// Emits no warning in Xcode 15b5
let a = try await client.someDeprecatedMethod()

// Emits a warning 
let b = try await erasedClient.someDeprecatedMethod()
```

**Comment by czechboy0** [comment]
I'm able to reproduce, let me fix this quickly.
