### ISSUE TITLE
Support Unix Domain Socket Paths in AsyncHTTPClientTransport

### ISSUE THREAD

**Issue by luiabrah** [apple/swift-openapi-generator#151]
I currently can't find a way to make the underlying AsyncHTTPClient execute requests against a unix socket path. AsyncHTTPClient does support this as per the [docs](https://github.com/swift-server/async-http-client/tree/main):

```swift
let httpClient = HTTPClient(eventLoopGroupProvider: .createNew)
httpClient.execute(
    .GET,
    socketPath: "/tmp/myServer.socket",
    urlPath: "/path/to/resource"
).whenComplete (...)
```

This would be useful for developing a Swift docker client. The docker API uses unix socket paths: https://docs.docker.com/engine/api/sdk/examples/

I tried updating the OpenAPI spec with the following but this did not yield the desired result
```
servers:
  - url: /var/run/docker.sock
    description: Example service deployment.
```

Would this require creating a new transport or adding some modifications to existing the AsyncHTTPClientTransport?

**Comment by simonjbeaumont** [comment]
@luiabrah thanks for reaching out!

You'll need to specify the server URL in the OpenAPI document as `http+unix://<percent-encoded-socket-path>/<resource-path>`; in your case:

```
servers:
  - url: http+unix://%2Fvar%2Frun%2Fdocker.sock
    description: Example service deployment.
```

---

Alternatively, if you don't want to put this into the OpenAPI document, then you'll need to make use of `URL.init(httpURLWithSocketPath:)` when creating the client—this is an extension provided by the `AsyncHTTPClient` module, which takes care of using this URL convention for the unix domain socket.

```swift
import AsyncHTTPClient
import Foundation
import OpenAPIRuntime
import OpenAPIAsyncHTTPClient

// Create an HTTP client.
let httpClient = HTTPClient(eventLoopGroupProvider: .createNew)
defer { try? httpClient.syncShutdown() }

// Create an API client.
let client = Client(
    serverURL: URL(httpURLWithSocketPath: "/tmp/example.sock")!,
    transport: AsyncHTTPClientTransport(
        configuration: AsyncHTTPClientTransport.Configuration(client: httpClient)
    )
)
```

**Comment by luiabrah** [comment]
That did the trick! Thank you. Closing issue
