### ISSUE TITLE
[Development] Not Running PR checks on draft PRs

### ISSUE THREAD

**Issue by denil-ct** [apple/swift-openapi-generator#163]
Can we skip running the PR checks if the PR is in draft state, and only run when its marked ready for review?
I feel like its quite wasteful to run checks for PR's that are in draft.

Thoughts?

**Comment by czechboy0** [comment]
@yim-lee is that an option in our CI?

**Comment by yim-lee** [comment]
I don't see an option specifically for draft PRs, but one could add `[skip ci]` (square brackets required) in the PR title so CI doesn't get triggered (e.g. https://github.com/apple/swift-openapi-generator/pull/167). Would that work?

**Comment by denil-ct** [comment]
I see, and to run the tests I assume we call swift bot in the comments?
Or will changing the title be enough?

**Comment by yim-lee** [comment]
I think as long as you change the title, you can either trigger build via comment or pushing new commit.

**Comment by denil-ct** [comment]
Got it, thanks.
Closing the issue, as it has been resolved.
