### ISSUE TITLE
Enable documentation comment validation in swift-format

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#165]
(This is about the codebase of the generator, runtime, and transports, not about generated code.)

We should enable the following two rules in the `.swift-format` file of all our repos, to get more validation of documentation comments. I sometimes forget to rename properties in doc comments and this could help catch that. Plus it'll ensure that new code is documented properly.

- `ValidateDocumentationComments`
- `AllPublicDeclarationsHaveDocumentation`
- possibly other comments-related ones

**Comment by PARAIPAN9** [comment]
Would like to take this one if it's available

**Comment by czechboy0** [comment]
Yeah, go ahead!
