### ISSUE TITLE
Overriding path item parameters with operation parameters doesn't work

### ISSUE THREAD

**Issue by mh-dmclean** [apple/swift-openapi-generator#168]
Hello there,

I've recently started experimenting with the openapi-generator seeing if it could help make some things easier at work. The generator seems to work but leads to compilation errors when having overridden variables, Easily modifying the GreetingService example Apple provides can reproduce this problem. [Here](https://gist.github.com/mh-dmclean/14b26befc7ad5f3996bd53890ca4fbfc) is a link to a gist containing the modified example and the `Types.swift` that is outputted. The error itself is on Lines 58/59 on Types.swift in the gist.

Package.resolved revision: c181ed

**Comment by czechboy0** [comment]
Hi @mh-dmclean, you're right, great catch!

From the OpenAPI 3.0.3 specification for the Path Item -> parameters [^1]:

> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there.

But today, we simply concatenate the parameters from the path item level with those at operation level here: https://github.com/apple/swift-openapi-generator/blob/main/Sources/_OpenAPIGeneratorCore/Translator/Operations/OperationDescription.swift#L150

However, we should instead _replace_ any parameters we find at the path item level with one found for the operation, if they have the same location + name.

A contribution with a fix and a unit test for this would be much appreciated 🙂 

[^1]: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-7

**Comment by arthurcro** [comment]
Hi @czechboy0! 😄 I'm intreseted in contributing to [swift-openapi-generator](https://github.com/apple/swift-openapi-generator).  I'll happily look at this issue if not picked up yet! 🙂

**Comment by czechboy0** [comment]
Great, welcome, @arthurcro! Hopefully my previous comment has enough information to start on, and you might also want to check out https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.7/documentation/swift-openapi-generator/contributing-to-swift-openapi-generator. Let us know if you need any help! 🙏

**Comment by arthurcro** [comment]
I believe I found a first decent fix for the issue. However, I'm struggling finding the right place to write a unit test to confirm it propoerly resolves the issue. 😄 
I did not find isolated unit tests testing `OperationDescription` since it's mostly tested through other tests. Could you maybe help me find the right place to add a great unit test? 🙂 

> However, we should instead replace any parameters we find

Finally, I'm wondering about performance since `allParameters` is a computed variables, are there any concerns regarding adding logic to replace some parameters that would be run every time this property is accessed? 🤔

**Comment by czechboy0** [comment]
Open the PR without the test and we'll discuss there what the best way to test it is.

Performance won't be an issue, today we recalculate a bunch of things repeatedly to avoid having to worry about cache invalidation, so it's fine. Generator complexity and maintainability is more important to us as the moment.

**Comment by arthurcro** [comment]
Here is the draft PR https://github.com/apple/swift-openapi-generator/pull/183/! 
Please let me know what you think when you get a chance 🙂
