### ISSUE TITLE
Enforce error diagnostics by aborting execution

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#180]
I vote we keep it; maybe even rename it fatal. WDYT? Could you open an issue and we can converge on a stance? Even if we end up removing it, we can close the loop on this.

_Originally posted by @simonjbeaumont in https://github.com/apple/swift-openapi-generator/pull/178#discussion_r1288038440_
            
See the conversation above.

Today, we have the issue that `.error` diagnostics don't terminate execution. We should decide whether to remove that error severity, and simply use error throwing to propagate fatal issues, or to somehow make emitting an error diagnostic become fatal.

**Comment by czechboy0** [comment]
@simonjbeaumont If we keep it, we have to find a way to propagate the signal that an error diagnostic was emitted to the generator. I'd like to avoid using `fatalError` (as that produces a crash log), and ideally have something testable (so `exit(1)` also isn't great).

But I wonder if we're over-engineering it. Essentially, the place that emits the error diagnostic wants to terminate execution anyway, which is what error throwing is for in Swift. Otherwise we need to find a way that some code in the generator emits an error diagnostic, which gets added to the diagnostic collector, and the signal that it was fatal is propagated back to the caller. Maybe the call to `emit` can just throw if the severity is `.error`? That'd work, I think.

**Comment by simonjbeaumont** [comment]
> Maybe the call to `emit` can just throw if the severity is `.error`? That'd work, I think.

That works for me.

**Comment by czechboy0** [comment]
Ugh, I forgot that `emit` isn't throwing today. We can change that though.

**Comment by czechboy0** [comment]
@arthurcro, sure, go ahead! 🙏

**Comment by arthurcro** [comment]
Hi! :wave: I had a chance to look at implementing this change. 
If my understanding is correct we want to change `DiagnosticCollector.emit(_:)` to be throwing. I am wondering if this is the best approach to propagate fatal issues.

First, changing the `DiagnosticCollector` to:

```swift
public protocol DiagnosticCollector {
  /// Submits a diagnostic to the collector.
  /// - Parameter diagnostic: The diagnostic to submit.
  /// - Throws: Throws when the diagnostic severity is `error`.
  func emit(_ diagnostic: Diagnostic) throws
}
```

would be an API breaknig chnge. 

Further, although it would be mentioned in the documentation of `DiagnosticCollector` there is no way to enforce that a error diagnostic would make  all the implementations of `DiagnosticCollector`  actually throw an error which mght be misleading.

Lastly, when the caller wants to emit a diagnostic, having to `try` to emit the diagnostic implies that emiting could fail. However, that's not always true, a diagnsotic collector implementation could log the error diagnoctic, so succeed at recieving the error and then throw.

It feels to me like emiting a diagnostic and throwing a fatal diagnsotic should be handled seperately. Maybe that's the way we want to go and I'm not sure what a better alternative would be but I wanted to share my thoughts here to resume the discussion.

**Comment by czechboy0** [comment]
Actually, another idea that should address these issues.

Create a new concrete reference type `DiagnosticSubmitter`, which holds a reference to a `DiagnosticCollector`.

```swift
final class DiagnosticSubmitter {
  private let collector: any DiagnosticCollector
  init(collector: any DiagnosticCollector) {
    self.collector = collector
  }

  func submit(_ diagnostic: Diagnostic) throws {
    collector.emit(diagnostic)
    if diagnostic.severity == .error {
      throw diagnostic
    }
  }
}
```

And then move the utility functions like `emitUnsupported...` onto the submitter, as `submitUnsupported...`.

This way, we can enforce the unified behavior without asking all collectors to manually implement it. What do you think?

**Comment by arthurcro** [comment]
This makes a lot of sense to me! I'll try it out, thank you for the great suggestion! 🙂

**Comment by simonjbeaumont** [comment]
@arthurcro just checking in to see if you still plan to work on this? If not, no problem, we can unassign it.

**Comment by PARAIPAN9** [comment]
Hello!! It's been a while, but I'm back and eager to contribute again to the generator! Is this issue still available?

**Comment by simonjbeaumont** [comment]
@PARAIPAN9 awesome, and welcome back! Yep, go ahead. I'll assign this one to you.

If you're generally happy to help and would like a steer on what would be high value, let us know and we could point to specific issues you might like to try. Especially if you have particular Swift learning goals etc.

**Comment by simonjbeaumont** [comment]
Just a heads up: some of the earlier discussion happened pre 1.0 so we'll now need to be more conscious about a solution that doesn't break API.

**Comment by PARAIPAN9** [comment]
> @PARAIPAN9 awesome, and welcome back! Yep, go ahead. I'll assign this one to you.
> 
> If you're generally happy to help and would like a steer on what would be high value, let us know and we could point to specific issues you might like to try. Especially if you have particular Swift learning goals etc.

Thank you for the warm welcome, I'm indeed open to suggestions on high-value issues. My current learning goals are to deepen my understanding of Swift, particularly in areas of low-level concepts, performance, optimizations, and generics.

**Comment by arthurcro** [comment]
Hi @simonjbeaumont! I apologise I did not react to your previous tag, I completely missed it. 
Thank you @PARAIPAN9 for taking over this! 🙇🏻

**Comment by simonjbeaumont** [comment]
> Hi @simonjbeaumont! I apologise I did not react to your previous tag, I completely missed it. Thank you @PARAIPAN9 for taking over this! 🙇🏻

@arthurcro No problem at all.  You'll always be welcome to dive in again if you have the time and inclination and, if not, thank you for your original interest and effort!

**Comment by simonjbeaumont** [comment]
> My current learning goals are to deepen my understanding of Swift, particularly in areas of low-level concepts, performance, optimizations, and generics.

@PARAIPAN9 Great, we'll sync up off-issue ❤️

**Comment by arthurcro** [comment]
>@arthurcro No problem at all. You'll always be welcome to dive in again if you have the time and inclination and, if not, thank you for your original interest and effort!

@simonjbeaumont It's been a while, I would love to dive in this awesome project again and contribute. If you have anything in mind I can help with, I'm up for it! 😃
