### ISSUE TITLE
Fix warning in generated server when no operations are included in the OpenAPI doc

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#190]
It's legal to have no operations in the OpenAPI doc, e.g. just have schemas.

Today, when someone generates a serve with such a doc, they'll get a warning because the variable `server` isn't used in the generated `registerHandlers` method.

Let's fix it by only generating this initializer if there's at least one operation. Otherwise keep the method empty.

**Comment by arthurcro** [comment]
Hey there!
I would be happy to take a look at fixing this! 😊

**Comment by czechboy0** [comment]
Sounds good, @arthurcro, let us know if you need any help!
