### ISSUE TITLE
Set Swift as the default language in the Info.plist of the docc bundles

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#20]
Set Swift as the default language in the Info.plist of the docc bundles.

This is so that code listings use Swift syntax highlighting by default.

**Comment by denil-ct** [comment]
Is this about setting the `CDDefaultCodeListingLanguage` key to swift in the plist?
If so, can we add the `CDAppleDefaultAvailability` to the plist as well?

**Comment by czechboy0** [comment]
@denil-ct Yup, that default listing language key is what we need.

Default availability is trickier, we don't want to have to update it in multiple places, ideally docc would pick it up from the Package.swift `platforms` key. But you can file a separate issue tracking this, we don't want to broaden this issue.
