### ISSUE TITLE
Consider the Client being generic over Transport/Middlewares

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#23]
Might result in better performance as it'd avoid existentials in the transport and middlewares properties.

However, we also should keep in mind the use case where the exact transport and set of middlewares used at runtime is not known at build time (e.g. by adding a middleware dynamically based on an environment variable, choosing a transport based on an env var - testing vs live, etc).

**Comment by czechboy0** [comment]
Important for UX, so to be considered or closed before 1.0.

**Comment by simonjbeaumont** [comment]
> Important for UX, so to be considered or closed before 1.0.

Shall we close this then?
