### ISSUE TITLE
Disable "respectsExistingLineBreaks" in .swift-format for more consistent styling

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#230]
Disable "respectsExistingLineBreaks" in .swift-format for more consistent styling.

Today, `respectsExistingLineBreaks` is enabled, which means that it depends on how you write the code before running the formatter, and it affects the output. That's not ideal, and is different than the setting we have for formatted code, so affects #40.

This should be done as a single PR, as it'll cause some churn.

**Comment by glbrntt** [comment]
Would disabling this rule remove all unnecessary line breaks?

E.g. would

```swift
func foo() {
  let bar = try makeBar()
  
  let baz = process(bar)
  baz.doSomething()
}
```

become the following?

```swift
func foo() {
  let bar = try makeBar()
  let baz = process(bar)
  baz.doSomething()
}
```

**Comment by czechboy0** [comment]
No, it leaves those alone. It only reformats line breaks around source code, it seems: https://github.com/apple/swift-openapi-generator/pull/231

**Comment by glbrntt** [comment]
Oh that seems reasonable then. Saying that, from the diff I'm not convinced this makes the code any easier to read. In fact some places it worsens readability. Perhaps other rules need tweaking when enabling this as well.

A few examples:

```swift
} catch {
        XCTFail(error.localizedDescription, file: file, line: line)
}
```

changed to

```swift
} catch { XCTFail(error.localizedDescription, file: file, line: line) }
```

and

```swift
    public static func error(
        message: String,
        location: Location? = nil,
        context: [String: String] = [:]
    ) -> Diagnostic {
        .init(severity: .error, message: message, location: location, context: context)
    }
```

changed to

```swift
    public static func error(message: String, location: Location? = nil, context: [String: String] = [:]) -> Diagnostic
    { .init(severity: .error, message: message, location: location, context: context) }
```

**Comment by czechboy0** [comment]
Yeah I don't love the bias towards single line scopes either. I'll take a look at the rules if we can't opt out of that.

**Comment by czechboy0** [comment]
Sure @PARAIPAN9, although it might result in a big diff, so maybe you could look into landing this one first?

**Comment by PARAIPAN9** [comment]
Sure, thanks!!
