### ISSUE TITLE
Enhance generator to Support Local File References in OpenAPI Files

### ISSUE THREAD

**Issue by bartoszirzyk** [apple/swift-openapi-generator#234]
I am working with a big service which provides OpenAPI documentation but currently generator cannot handle local references. I am getting an error:
`You cannot look up remote JSON references in the Components Object local to this file.`

It would be really handy, if this generator could parse such configurations.

**Comment by czechboy0** [comment]
Note that a workaround here is to use another tool that inlines the multiple documents into a single one, which you can then use with our generator.

**Comment by bartoszirzyk** [comment]
Yeah that’s what I’m going to do as a workaround. Wanted to point it out anyway
