### ISSUE TITLE
Is it compatible with Xcode Cloud

### ISSUE THREAD

**Issue by leecaa** [apple/swift-openapi-generator#246]
Can it be used normally on Xcode Cloud? Because it uses a plugin to generate code, I've encountered issues with other repositories where I didn't have write permissions on Xcode Cloud, which prevented the code from being generated normally. [[Link to GitHub issue]](https://github.com/mac-cain13/R.swift/issues/777)

Thanks for any reply

**Comment by simonjbeaumont** [comment]
@leecaa yes, it’s possible. But as you noted, it requires permissions. This post on the developer forums explains how to get the plugin working in Xcode Cloud: https://developer.apple.com/forums/thread/732893. 

Hope this helps.
