### ISSUE TITLE
Emit a specific error when a cycle is encountered

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#247]
I was trying out this generator for the first time and triggered this issue. The problem is that the error message can be misleading:

`Encountered a JSON Schema $ref cycle that prevents fully dereferencing document at '#/components/schemas/KommentarDTO'. This type of reference cycle is not inherently problematic for JSON Schemas, but it does mean OpenAPIKit cannot fully resolve references because attempting to do so results in an infinite loop over any reference cycles. You should still be able to parse the document, just avoid requesting a locallyDereferenced() copy.`

I understood this to mean I have to change some generator config setting to not try to request a locallyDereferenced copy. Spent some time trying to "fix" this first ☺️. Only once I read the source code comment I now understand that there is no workaround at this moment and that the openapi file that I would like to use will not work. I think it would be useful to catch this specific error and state that cyclic jsons are not supported yet?

_Originally posted by @hactar in https://github.com/apple/swift-openapi-generator/issues/130#issuecomment-1707349526_

**Comment by czechboy0** [comment]
Agreed that this could be improved, @hactar - we welcome contributions in this area 🙂

**Comment by czechboy0** [comment]
No need to do this if we fix #70 soon.

**Comment by davidcruzcs** [comment]
+1

**Comment by czechboy0** [comment]
I'm already working on recursive types, so this issue will not be fixed.
