### ISSUE TITLE
Build errors when following WWDC 23 'Meet Swift OpenAPI Generator' video

### ISSUE THREAD

**Issue by alexanderulanch** [apple/swift-openapi-generator#252]
**Commit hashes:** 
- `swift-openapi-generator`: `5dbd05d3d782f0b19292e90ddc21a11e242d510b`
- `swift-openapi-runtime`: `9b003cc1f189953b6266bf89cd37d8146e183774`
- `swift-openapi-urlsession`: `8d34af5db44be4825749259dbb38e5e11a4c48da`

**Context:** 
While following along with the 'Meet Swift OpenAPI Generator' WWDC 23 Developer video, I ran into build errors relating to the `swift-openapi-generator` package.

**Steps to reproduce:**
1. Install the 3 required package dependencies to a new project (`swift-openapi-generator`, `swift-openapi-runtime`, & `swift-openapi-urlsession`).
2. Configure target to use the `swift-openapi-generator` plugin in the target settings.
3. Add the `openapi-generator-config.yaml` and `openapi.yaml` (I used the code provided in the demo).
4. After building the app, I get multiple swift package product errors. See attached build report below.

**Operating System:** macOS Sonoma Version 14.0 Beta (23A5312d)

```bash
$ swift --version
swift-driver version: 1.87 Apple Swift version 5.9 (swiftlang-5.9.0.124.4 clang-1500.0.38.1)
Target: arm64-apple-macosx14.0
```

**Build Report**
[Build swift-openapi-test_2023-09-08T01-31-40.txt](https://github.com/apple/swift-openapi-generator/files/12555921/Build.swift-openapi-test_2023-09-08T01-31-40.txt)

**Comment by czechboy0** [comment]
Your `swift-openapi-test` executable seems to be linking the generator directly, instead of just using it as a plugin.

Can you make sure the checkboxes are unchecked when adding the plugin? See more in https://developer.apple.com/forums/thread/732178?answerId=756684022#756684022

**Comment by alexanderulanch** [comment]
That did the trick. Thank you!
