### ISSUE TITLE
Use the `package` access modifier for generated code

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-openapi-generator#270]
Swift 5.9 adds the new `package` access modifier (see the [evolution proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md)). 

This is a very natural fit for the generated code as:
- Users are encouraged to wrap the generated types rather than vending them directly as part of their package.
- Users are encouraged to generate code for into separate modules per document.

However, it's likely that some users will still want to vend generated code.

I think the generator should provide a configuration option for visibility so that the user can decide. The default should likely be set to the new `package` access level.

**Comment by czechboy0** [comment]
Agreed, we should offer:
- package (new option, new default) - this will be a breaking change, so needs to happen e.g. in 0.3.0 or 1.0
- public (old default)
- internal (new option)

**Comment by czechboy0** [comment]
This is blocked on 5.9 adoption: #75
