### ISSUE TITLE
Unknown configuration options should throw an error

### ISSUE THREAD

**Issue by simonjbeaumont** [apple/swift-openapi-generator#276]
Example, if you use `featureFlag` instead of `featureFlags`:

```yaml
generate:
  - types
featureFlag:
  - nullableSchemas
```

This is easy to do because the CLI is `--feature-flag` (taking multiple).
 
We already print the following to stdout:

```none
Swift OpenAPI Generator is running with the following configuration:
- OpenAPI document path: ...
- Configuration path: ...
- Generator modes: types, client
- Feature flags: ...
- Output file names: Types.swift, Client.swift
- Output directory: ...
- Diagnostics output path: <none - logs to stderr>
- Current directory: ...
- Plugin source: <none>
- Is dry run: false
- Additional imports: <none>
```

Probably should print something here about unknown keys?

**Comment by czechboy0** [comment]
We should probably fail on unknown keys, tbh. The danger of this issue is too real. We already fail if you provide an invalid feature flag, so I'd be supportive of going even more strict.

**Comment by simonjbeaumont** [comment]
Yeah, OK. I can see this biting with the `additionalImports` (cf. `--additional-import`) too.

**Comment by simonjbeaumont** [comment]
Is technically breaking an interface, so propose we pull into the 1.0 milestone.

**Comment by czechboy0** [comment]
And I'd be for an error here, not even a warning. It's invalid input and the adopter should fix it ASAP, otherwise they might think they're enabling a feature or similar but they're not.

**Comment by czechboy0** [comment]
> Is technically breaking an interface, so propose we pull into the 1.0 milestone.

True, changed.

**Comment by PARAIPAN9** [comment]
Hello again, I'd like to try this out if possible.

**Comment by czechboy0** [comment]
@PARAIPAN9, sure go ahead! 🙏
