### ISSUE TITLE
URIEncoder does not correctly encode primitive collections

### ISSUE THREAD

**Issue by bfrearson** [apple/swift-openapi-generator#292]
Trying to encode a primitive collection (e.g. an array of Strings) from a Codable type fails because the URIEncoder rejects nested object types.

It would be beneficial to support this, as there we may have query items or forms which contain multiple values for the same key. I believe `URIDecoder` already does support collecting identical keys into a collection.

**Comment by czechboy0** [comment]
@bfrearson can you provide an example of the Codable type?

Which one doesn't work, and what's the error?

```swift
typealias Foo = [String]
```

or 

```swift
struct Foo: Codable {
  var bar: [String]
}
```

I'd expect the former to work, but possibly not the latter.

**Comment by czechboy0** [comment]
Ping @bfrearson, when you have a moment, I'm wondering if you remember which case from the above was failing for you, thanks!

**Comment by bfrearson** [comment]
Hey, sorry for the delay - been super slammed at the moment!

It would be the second option that failed:

``` swift
struct Foo: Codable {
  var bar: [String]
}
```

**Comment by czechboy0** [comment]
Yes, that's expected. Nested containers are not supported, only top level containers. So the array has to be the top level item, and the name `bar` should be the name of the parameter instead.

**Comment by czechboy0** [comment]
It's also possible you're trying to do #259?

**Comment by bfrearson** [comment]
Yes it looks as if this covers the same issue.

Tbh this was an abstract thought I had while working on the encoder, rather than a real world barrier that I hit. I don't think any of the APIs I'm using personally need to support this, but I think there should definitely be support for handling them.

**Comment by czechboy0** [comment]
Understood, thank you. Let me close this issue then and reference it from #259, as it already covers this then.
