### ISSUE TITLE
Update urlsession transport package for 0.3.0 release

### ISSUE THREAD

**Issue by denil-ct** [apple/swift-openapi-generator#304]
Currently the urlsession transport is limited to 0.2.x versions of the runtime, but Xcode defaults to 0.3.0 version as its the latest, hence not allowing to add the transport library.

I'm not raising PR as 0.3.0 release is marked as a breaking change. Let me know if its okay to bump the versions, or are there major changes?

**Comment by czechboy0** [comment]
0.3.0 is still not fully released. It's staged. First we release the runtime library, give a few days for transports to release their 0.3.0 versions, and finally we release 0.3.0 of the generator. That's expected to happen early next week.

So this is all part of the process. Folks should continue to use 0.2.x of all packages for now.
