### ISSUE TITLE
Build Error: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by byaruhaf** [apple/swift-openapi-generator#307]
Issue: Build Error
Fault Code: Command PhaseScriptExecution failed with a nonzero exit code
Environment: Version 15.0 (15A240d)
OpenAPI Spec: https://github.com/byaruhaf/MoMoOpenAPISpec/blob/main/Remittance/openapi.yaml

Summary:
Build error occurs when generating Remittance spec using plugin.

Repo to show the issue:
https://github.com/byaruhaf/RemittanceClient

Plugin Version:

swift-openapi-generator: 0.2.3
swift-openapi-runtime: 0.2.5
swift-openapi-urlsession: 0.2.2

Error:

```bash
_OpenAPIGeneratorCore/ContentType.swift:180: Precondition failed: Invalid ContentType string, must have 2 components separated by a slash.
/Users/alphabo/Library/Developer/Xcode/DerivedData/RemittanceClient-bdbwvhgjtiqmgialfpdgrmptmvif/Build/Intermediates.noindex/RemittanceClient.build/Debug/RemittanceClient.build/Script-9230177165958809893.sh: line 17: 45194 Illegal instruction: 4  /usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/lw/jpcnn99x3lz9j0txyk_v2xlr0000gn/T\")
)
(deny file-write*
    (subpath \"/Users/alphabo/RemittanceClient\")
)
(allow file-write*
    (subpath \"/Users/alphabo/Library/Developer/Xcode/DerivedData/RemittanceClient-bdbwvhgjtiqmgialfpdgrmptmvif/SourcePackages/plugins/remittanceclient.output/RemittanceClient/OpenAPIGenerator\")
)
" "/${BUILD_DIR}/${CONFIGURATION}/swift-openapi-generator" generate /Users/alphabo/RemittanceClient/Sources/openapi.yaml --config /Users/alphabo/RemittanceClient/Sources/openapi-generator-config.yaml --output-directory /Users/alphabo/Library/Developer/Xcode/DerivedData/RemittanceClient-bdbwvhgjtiqmgialfpdgrmptmvif/SourcePackages/plugins/remittanceclient.output/RemittanceClient/OpenAPIGenerator/GeneratedSources --plugin-source build
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by czechboy0** [comment]
Hi @byaruhaf, the OpenAPI document has an invalid content type here: https://github.com/byaruhaf/MoMoOpenAPISpec/blob/2ad08a336924fd83845d96081dd99f3e5566221a/Remittance/openapi.yaml#L37C35-L37C35

That's why it's failing. You can also use an OpenAPI linter command-line tool to check that the document doesn't contain errors before passing it to the generator, for easier debugging.

**Comment by byaruhaf** [comment]
Thank's will take it up with the API provider
