### ISSUE TITLE
Invalid reference to `OpenAPIRuntime.Request` in generated code using runtime version `0.3.0`

### ISSUE THREAD

**Issue by devraj** [apple/swift-openapi-generator#309]
Commit hash: 1eaf236

## Context:
I am following [XCode client](https://swiftpackageindex.com/apple/swift-openapi-generator/0.2.3/tutorials/swift-openapi-generator/clientxcode) guide to generate a client (for purposes of reporting this bug I am using the [pestore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml) file found on Github).

If I use the latest release of `swift-openapi-runtime` i.e `0.3.0` then I get the following errors in `Client.swift`:

Line `46`: No type named 'Request' in module `OpenAPIRuntime`

```swift
var request: OpenAPIRuntime.Request = .init(path: path, method: .get)
```

and on Line 41: Type of expression is ambiguous without a type annotation

```
try await client.send(
```

These errors aren't present when using `v0.2.x` of `swift-openapi-runtime` and `swift-openapi-urlsession`. 

Additional context, I was originally trying to generate a client for Github's API which failed to build with `swift-openapi-runtime==0.3.0` and decided to fallback to using a simpler example to see if this issue really presented itself.

## Steps to reproduce the error:
1. In XCode add `swift-openapi-generator==0.2.3`, `swift-openapi-runtime==0.3.0`, `swift-openapi-urlsession=0.3.0` 
1. Download and add `petstore.yaml` and configure the generator as [descried in this tutorial](https://swiftpackageindex.com/apple/swift-openapi-generator/0.2.3/tutorials/swift-openapi-generator/clientxcode).
1. Run the build to find the reported errors in every occurrence of a call to `OpenAPIRuntime.Request` or the `client.send` call.
1. Now revert `swift-openapi-runtime==0.2.5` and `swift-openapi-urlsession=0.2.2`
1. Run the build again to see the build succeed. 
1. Inspect `Client.swift` to find the `OpenAPIRuntime.Request` references still present but the build succeeds.

## Environment:
- XCode Version: 15.0 `15A240d`
- macOS Version: 14.0

Swift Version:
```
Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
```

**Comment by czechboy0** [comment]
Version 0.3.0 of the generator is not released yet, so you'll need to use the latest versions of 0.2.x of all three packages.

Mixing 0.2.x and 0.3.x does not work, as pre-1.0, minor versions contain API-breaking changes.
