### ISSUE TITLE
Add CI for Swift 5.10

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#316]
Add CI for Swift 5.10

**Comment by simonjbeaumont** [comment]
Resolved by:
- https://github.com/apple/swift-openapi-generator/pull/317
- https://github.com/apple/swift-openapi-runtime/pull/57
- https://github.com/swift-server/swift-openapi-async-http-client/pull/19
- https://github.com/apple/swift-openapi-urlsession/pull/16
