### ISSUE TITLE
Unable to build generated code with Address Sanitizer turned on

### ISSUE THREAD

**Issue by romanzhukovTB** [apple/swift-openapi-generator#318]
Commit hash: 5e47a80cf064fe8d4ab864d68ce3fed3ed642672

Context:
Hey all, I'm trying to use Address Sanitizer in my project that has a generated API client in it, and when I turn it on it fails to build on the `swift-openapi-generator` script phase with `Illegal Instruction`. I'm able to reproduce this on the `GreetingService` example.

Steps to reproduce:
1. Open GreetingService example package in Xcode
2. Modify the active scheme to enable Address Sanitizer
3. Build
4. Observe the following error:
```
/Users/<redacted>/Library/Developer/Xcode/DerivedData/GreetingService-frmvebyigiwveqgyxplotzirotiq/Build/Intermediates.noindex/GreetingService.build/Debug/GreetingService.build/Script-5354115775743181209.sh: line 17: 79185 Illegal instruction: 4  /usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/g2/ttgz3p7d7y79gz2lh99jcwf00000gp/T\")
)
(deny file-write*
    (subpath \"/Users/<redacted>/dev/swift-openapi-generator/Examples/GreetingService\")
)
(allow file-write*
    (subpath \"/Users/<redacted>/Library/Developer/Xcode/DerivedData/GreetingService-frmvebyigiwveqgyxplotzirotiq/SourcePackages/plugins/greetingservice.output/GreetingService/OpenAPIGenerator\")
)
" "/${BUILD_DIR}/${CONFIGURATION}/swift-openapi-generator" generate /Users/<redacted>/dev/swift-openapi-generator/Examples/GreetingService/Sources/GreetingService/openapi.yaml --config /Users/<redacted>/dev/swift-openapi-generator/Examples/GreetingService/Sources/GreetingService/openapi-generator-config.yaml --output-directory /Users/<redacted>/Library/Developer/Xcode/DerivedData/GreetingService-frmvebyigiwveqgyxplotzirotiq/SourcePackages/plugins/greetingservice.output/GreetingService/OpenAPIGenerator/GeneratedSources --plugin-source build
```

```
$ swift --version 
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

OS: Sonoma 14.0
```
Darwin username - LWX0NQDR67 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64
```

**Comment by czechboy0** [comment]
Did it produce a crashlog as well? I suspect it's trying to load something on launch that is prevented by the sandbox. I think it might be mentioned in the crashlog, if one was created.

**Comment by czechboy0** [comment]
Also wondering if plugins themselves should be built with sanitizers etc? @neonichu

**Comment by neonichu** [comment]
> Also wondering if plugins themselves should be built with sanitizers etc? @neonichu

Would be nice, yes, but today we don't respect essentially any settings for plugins (in either Xcode or SwiftPM CLI).

**Comment by czechboy0** [comment]
@neonichu Sorry, I meant the other way around. From the above it seems the sanitizer is breaking the plugin (TBD why), but should build time plugins inherit sanitizers meant for runtime components?

**Comment by neonichu** [comment]
Ah I see, not sure, maybe not? I guess the executables to get build using the scheme option, so if build commands use any executables, those would have sanitizers enabled.

**Comment by romanzhukovTB** [comment]
> Did it produce a crashlog as well? I suspect it's trying to load something on launch that is prevented by the sandbox. I think it might be mentioned in the crashlog, if one was created.

I don't see any crash logs, it doesn't look like it's crashing to me. That phase execution error that I sent is the only thing I see in the build log (+ the exports that happen before the script is run)

**Comment by czechboy0** [comment]
I filed this on Xcode (rdar://116810597), cc @neonichu. Not an issue specific to Swift OpenAPI Generator, I suspect any build plugin would hit this.

Thank you @romanzhukovTB for flagging this!
