### ISSUE TITLE
visionOS should not show compatibility with the plugin

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#327]
We only support macOS and Linux for running the build plugin, but SPI is also now showing visionOS. We should expand our #if guards.

**Comment by czechboy0** [comment]
We should double check when the visionOS platform name was added to SwiftPM, as this might require the 5.9 tools version - possibly blocked.

**Comment by simonjbeaumont** [comment]
I think we're fine. 

We make the following check[^1], which should definitely fail on visionOS.

```swift
#if !(os(macOS) || os(Linux))
#error(
    "_OpenAPIGeneratorCore is only to be used by swift-openapi-generator itself—your target should not link this library or the command line tool directly."
)
#endif
```

[^1]: https://github.com/apple/swift-openapi-generator/blob/23073d4/Sources/_OpenAPIGeneratorCore/PlatformChecks.swift#L17-L21
