### ISSUE TITLE
Can't specify Content-Length header for HEAD requests

### ISSUE THREAD

**Issue by tib** [apple/swift-openapi-generator#328]
I just discovered a small issue that I can't solve, as far as I know, according to the HTTP [specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD), a HEAD request should return the Content-Length of the requests as if it was a GET request, but right now I'm not able to override this header, even if I explicitly set it up in the OpenAPI document.

Are you aware of this issue, or is there some kind of workaround? Maybe am I missing something? Thank you for the help in advance. 🙏

**Comment by czechboy0** [comment]
Hi @tib, which transport are you using? Can you show a snippet of openapi of your operation? Thanks

**Comment by tib** [comment]
I'm working on a sample repository, will share it later on, I just need some time to finish it.

**Comment by tib** [comment]
Invited both you & @simonjbeaumont to a private repo under my organization (Binary Birds), will push the code later on today.

**Comment by tib** [comment]
FYI: this works perfectly fine using the Hummingbird transport service, I've created a [fix](https://github.com/swift-server/swift-openapi-vapor/pull/5) for the Vapor transfer service layer.
