### ISSUE TITLE
Lost info in errors

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-openapi-generator#336]
Error messages in [OpenAPI-Runtime](https://github.com/search?q=repo:apple/swift-openapi-runtime%20localizedDescription&type=code) package and also in here seem to be using `localizedDescription` to be converted to string descriptions.

`localizedDescription` is almost always useless in a server environment and only causes debugging pain, other than having numerous weird/buggy behaviors: https://github.com/apple/swift/issues/68102

I'm not sure if it is of any help even in a iOS environment for this package. 

What i can think of is to just move all the errors to contain the actual other underlying error, instead of just a representation.
This enables users to use `"\(error)"` or even `String(reflecting: error)` if needed. There could also be an option to retrieve a vague un-debuggable error from the OpenAPI error types if there is need for that.

**Comment by czechboy0** [comment]
Hi @MahdiBM, there's a related issue that's in my plate for next week: https://github.com/apple/swift-openapi-generator/issues/302

Would fixing that make things better for you?

**Comment by MahdiBM** [comment]
@czechboy0 I suspect so, since from what I understand the original error will need to be there (basically).

**Comment by czechboy0** [comment]
Okay, let me close this one then and please subscribe to the other one for updates.
