### ISSUE TITLE
Validate references in validateDoc

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#341]
Validate references in validateDoc to reject unsupported/dead references at the very start, to produce a good error.

Would likely mean walking all references and checking that they're internal and can be looked up in components. Throw a descriptive error if one is found that fails that.

Apply this _after_ filtering, to avoid throwing an error about a part of the document that the adopter doesn't want to generate anyway.

**Comment by PARAIPAN9** [comment]
Hey, I'd like to start tackling this issue. It just feels like the next step after diving into #342. 😆

**Comment by czechboy0** [comment]
Yeah - great!
