### ISSUE TITLE
Validate content-type strings in validateDoc

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#342]
Validate content-type strings in validateDoc, similar to https://github.com/apple/swift-openapi-generator/issues/341, to catch invalid inputs at the very start.

Would mean trying to parse the content type of all places that can have content in the doc, and throwing a descriptive error if it cannot be parsed correctly. (This means a malformed string, like empty, one without `foo/bar` two components, etc.)

There are many docs with malformed content types and it'd be good to emit good errors early in the process to allow the adopter to fix it up.

**Comment by PARAIPAN9** [comment]
Hello, I'm interested in working on this issue, if available.

**Comment by czechboy0** [comment]
Thanks @PARAIPAN9, go ahead!

**Comment by simonjbeaumont** [comment]
@PARAIPAN9 💪
