### ISSUE TITLE
Change HTTPBody length stored integer from Int to Int64

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#354]
Change HTTPBody length stored integer from Int to Int64.

This will be an API break, so must happen as part of a minor before 1.0 or as part of 1.0 itself.

**Comment by simonjbeaumont** [comment]
> This will be an API break, so must happen as part of a minor before 1.0 or as part of 1.0 itself.

To help roll this out, we could rename this type at the same time to `contentLength` and deprecate `length`?

**Comment by czechboy0** [comment]
Yeah that's a good idea, that way we can land now and clean up the deprecated one for 1.0.
