### ISSUE TITLE
ServerTransport ability to support Vapor's RoutesBuilder HTTPBodyStreamStrategy parameter.

### ISSUE THREAD

**Issue by alex1704** [apple/swift-openapi-generator#360]
Hi,
I'm using `VaporTransport` and my goal is to manipulate Vapor's `RoutesBuilder`'s `body` param in signature:

```
extension RoutesBuilder {
  public func on<Response>(
        _ method: HTTPMethod,
        _ path: [PathComponent],
        body: HTTPBodyStreamStrategy = .collect,
        use closure: @Sendable @escaping (Request) async throws -> Response
    ) -> Route
```
Implementation of `VaporTransport`:
```
extension VaporTransport: ServerTransport {
  public func register(
        _ handler: @Sendable @escaping (
            HTTPTypes.HTTPRequest, OpenAPIRuntime.HTTPBody?, OpenAPIRuntime.ServerRequestMetadata
        ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?),
        method: HTTPRequest.Method,
        path: String
    ) throws {
        self.routesBuilder.on(
            HTTPMethod(method),
            [PathComponent](path)
        )...
```
Are there any plans to extend `ServerTransport` protocol to accomplish this goal?

**Comment by czechboy0** [comment]
Hi @alex1704, that transport is owned by the Vapor team, so please open an issue on that repo (swift-server/swift-openapi-vapor). But I think they're just waiting for final fixes in Vapor before enabling request streaming. Tim and @MahdiBM can speak more to this.

**Comment by MahdiBM** [comment]
@alex1704 as @czechboy0 we're waiting on a fix to be able to enable streaming.
I haven fully investigated it but i'll create an issue about being able to configure that parameter in the Vapor transport. When the fix is there, i'll look into the issue as well.

**Comment by czechboy0** [comment]
@MahdiBM I don't think it should be a parameter, streaming should always be enabled, that's what all 3 other transports do. But yes it can only be enabled once Vapor isn't crashing when it's enabled, so let's hold off.

**Comment by czechboy0** [comment]
Waiting on https://github.com/vapor/vapor/pull/3096
