### ISSUE TITLE
Base64EncodedData initializer taking an array slice shouldn't have a label

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#368]
Base64EncodedData initializer taking an array slice shouldn't have a label.

```diff
- public init(data: ArraySlice<UInt8>)
+ public init(_ data: ArraySlice<UInt8>)
```

API breaking, do for 1.0.

**Comment by PARAIPAN9** [comment]
Hi, I'd be happy to take on the task of making this change.

**Comment by czechboy0** [comment]
Sure! If you could add the new one, but keep the existing one for now and mark it as deprecated, and we'll clean up the deprecated one for 1.0 later.
