### ISSUE TITLE
Custom imports for generated server / client code?

### ISSUE THREAD

**Issue by tib** [apple/swift-openapi-generator#371]
Hello,

I'd like to propose a feature request for the generator plugin (or looking for an anternative solution for my issue):

Consider `FooTypes` a library target, which exposes the objects in the `Types.swift` file. This is generated with the following configuration:

```yaml
generate:
  - types
```

Consider a second target (`FooServerKit`), which has the generator plugin configured to create the server or the client code (`Server.swift` or `Client.swift`).

```yaml
generate:
  - server (or client)
```

Now the problem is that the generated client / server code won't compile, since the required types are located under a different module name. Is it possible to import the module somehow or expose the types without using the `@_exported import FooTypes` workaround? 🤔 

I'm thinking about a new generator configuration, something like:

```yaml
generate:
  - server

server:
  imports:
    - FooTypes

client:
  imports:
    - FooTypes
```

This would would add an extra import line to the generated server / client source.

```swift
import FooTypes
```

What do you think about this? Am I missing something? Is this proposal something you'd consider implementing in the near future? Would you consider merging it if I make this happen? 😅

**Comment by tib** [comment]
Oh, nevermind, `additionalImports` was the thing I was [looking for](https://swiftpackageindex.com/apple/swift-openapi-generator/0.3.4/documentation/swift-openapi-generator/configuring-the-generator).

**Comment by simonjbeaumont** [comment]
@tib No problem—glad you found what you needed. FWIW, the `IntegrationTest`[^1] uses this feature, where the `Client` and `Server` targets both depend on a shared `Types` target, which allows for adding extensions to the generated types that can be used on both sides.

[^1]: https://github.com/apple/swift-openapi-generator/blob/main/IntegrationTest/Package.swift

**Comment by tib** [comment]
Many thanks, yeah I'm following somewhat the same technique and I'm re-using the types both on the client & server side. 💪
