### ISSUE TITLE
Throw error from `Middleware` without being wrapped in `ClientError`

### ISSUE THREAD

**Issue by madsodgaard** [apple/swift-openapi-generator#373]
Hi! I am trying to generate a Client for an internal API. The API returns all errors in a specific format:
```json
{
  "error": true,
  "code": "error_code",
  "message": "Some message"
}
```

I am trying to find a way to handle this for all my endpoints with this library. I really don't want to add extra code to every API call, where I handle the error response, because it always has the same format. Therefore I tried doing this with a `ErrorMiddleware`:
```swift
struct ErrorMiddleware: ClientMiddleware {
    private let decoder = JSONDecoder()
    
    func intercept(
        _ request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        baseURL: URL,
        operationID: String,
        next: @Sendable (HTTPTypes.HTTPRequest, OpenAPIRuntime.HTTPBody?, URL) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?)
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        let (response, body) = try await next(request, body, baseURL)
        
        guard response.status.kind == .clientError || response.status.kind == .serverError else {
            return (response, body)
        }
        guard let body else {
            throw APIError.badStatusCodeWithNoBody(response.status)
        }
        
        let errorResponse = try await decoder.decode(
            Components.Schemas._Error.self,
            from: Data(collecting: body, upTo: .max)
        )
        
        throw APIError.withPayload(errorResponse.toDomain())
    }
}
```
The problem is that the error is being wrapped in a `ClientError`, so I can't directly catch the `APIError` type at the callsite, I first have to check whether it is a `ClientError`, which is not really a type I want to leak through to the other domain modules. Is there any way to circumvent this behaviour? Or another way to achieve the generic handling of errors without `Middleware`?

This is how the generated `Client` is used:
```swift
return APIClient(
  registerUser: { @Sendable registerRequest in
    let user = try await client.registerUser(body: .json(registerRequest.toAPI())).created.body.json
    return user.toDomain()
}
```
I had an idea that maybe I could use a macro to wrap the methods in that handles the `.default` response and converts that to an `APIError`, but then I'd have to remember to do that for every method 😅 

Thanks!

**Comment by czechboy0** [comment]
The ClientError has an underlyingError property, which holds your original error. Would that work for you?

**Comment by simonjbeaumont** [comment]
@madsodgaard there's also some relevant discussion in #302 which might be useful for your use case.

**Comment by madsodgaard** [comment]
@simonjbeaumont @czechboy0 Thanks for taking a look at this! I already noticed the `underlyingError` property, but that would require that the modules that use my `APIClient` depend on the OpenAPI library as well to catch the errors, as they would first have to catch the `ClientError` and then check the type of `underlyingError`. My goal is really to make the `APIError` the type that is thrown when the user performs an API request, so that the only library that depends on this library is my live implementation of the`APIClient` protocol (which is my own protocol, which contains methods such as `getTodo`, `createTodo` etc).

Perhaps the only way is to really wrap all of my methods in `APIClient` to catch the `ClientError` and then convert to a `APIError`?

**Comment by czechboy0** [comment]
Yes wrapping the API is probably best here - allows you to hand-craft your library interface, but you still use the generated code as an implementation detail. https://swiftpackageindex.com/apple/swift-openapi-generator/0.3.4/documentation/swift-openapi-generator/api-stability-of-generated-code

**Comment by madsodgaard** [comment]
@czechboy0 You are thinking I have to do something like this, right?
```swift
struct APIClientLive: APIClient {
  func registerUser(registerRequest: RegisterRequest) async throws -> User {
                do {
                    let user = try await client.registerUser(body: .json(registerRequest.toAPI())).created.body.json
                    return user.toDomain()
                } catch let error as ClientError {
                    throw error.underlyingError
                }
            }
}
```
This combined with the `ErrorMiddleware` I presented in the post. Of course the downside of this I have many methods inside `APIClient`, so I would have to add this boilerplate code to every method (and remember to do so for new methods).

I am still not sure what the best way to handle this sort of error handling with this library is. From the discussion #302, if for example a `URLError` is thrown from the transport layer, that is the `Error` I want to throw to the caller of my `APIClient` methods, not a `ClientError`, because I don't want them to depend on `OpenAPIRuntime`.

**Comment by simonjbeaumont** [comment]
Can you confirm what sort of interface you'd like to vend to your adopters with your package? And what you want them to do with this error? 

Usually folks who are wrapping up the generated client in a curated API experience are doing so to deliberately shield users from any underlying details. These usually include that they are using the generator and whatever `ClientTransport` they decided to use under the hood. 

If you want your adopters to be exposed the `ClientTransport` choice, then maybe they should be providing it. But, at that point, maybe they should be using the generator directly since that's what it provides out of the box: a transport-agnostic implementation.

**Comment by czechboy0** [comment]
I'd second what @simonjbeaumont said. To also answer your question about the code snippet, @madsodgaard, since you are already wrapping every method, and providing

```swift
struct APIClientLive: APIClient {
  func registerUser(registerRequest: RegisterRequest) async throws -> User { ... }
}
```

then yes, I'd recommend also unwrapping the errors for your users, and completely hiding the fact that you're using Swift OpenAPI Generator under the hood.

You could write a util method like

```swift
func unwrappingError<R>(_ invocation: @autoclosure () async throws -> R) throws -> R {
    do {
        return try await invocation()
    } catch let error as ClientError {
        throw error.underlyingError
    }
}
```

which you could then use as:

```
struct APIClientLive: APIClient {
  func registerUser(registerRequest: RegisterRequest) async throws -> User {
    let user = try await unwrappingError(client.registerUser(body: .json(registerRequest.toAPI()))).created.body.json
    return user.toDomain()
  }
}
```

**Comment by madsodgaard** [comment]
@simonjbeaumont @czechboy0 Thanks! Yeah, so what I basically wanted to do was to not expose implementation details about using the OpenAPI library to the user of the package. I want them to access the API trough the `APIClient` protocol, which contains domain-specific methods such as `registerUser`. And since every error response from the API has the same JSON format, I want the users to be able to access any relevant information from the API error, such as the error message returned by the backend, hence why I wanted to throw an `APIError` instead of `ClientError`.

The `errorDescription` of `APIError` can then access the response the API returned and use that as a message that I can display to the user of the actual iOS app:
```swift
public enum APIError: LocalizedError {
    case badStatusCodeWithNoBody(Int)
    case withPayload(APIErrorPayload)
    
    public var errorDescription: String? {
        switch self {
        case .badStatusCodeWithNoBody(_):
            "Unknown error"
        case .withPayload(let payload):
            payload.message
        }
    }
}
```
Looks like doing the `unwrappingError` approach seems like the best option here. Thanks again for sharing your thoughts on this!

**Comment by czechboy0** [comment]
Great! Yeah we recommend wrapping the generated API instead of providing it to other people, that way you can keep evolving the OpenAPI doc while maintaining a stable API for your Swift users.

Closing the issue as resolved then. If you have some ideas of how this workflow could be improved, feel free to open a new issue describing a design, we also have a [proposal](https://swiftpackageindex.com/apple/swift-openapi-generator/main/documentation/swift-openapi-generator/proposals) process if you'd like to design and implement that feature, all up to you.
