### ISSUE TITLE
Custom header support on a client side.

### ISSUE THREAD

**Issue by yaroslavyaroslav** [apple/swift-openapi-generator#374]
Hi, I'm trying to convert [openai-openapi](https://github.com/openai/openai-openapi) in swift. It successfully creates `Client.swift` and `Types.swift` with complete set of methods, but I see no way to append there any custom header (e.g. `"Authorization: Bearer {token}"`, because it appears that header isn't the [String: String] dict (which I'm expecting for), but an array of `Operations.createChatCompletion.AcceptableContentType`, which contains a single value: `application/json`. The `Headers` in its turn is also not looks like being expected anything except available content header.

```swift
public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.createChatCompletion.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.createChatCompletion.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
``` 

```swift
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
```

Is this by design or do I'm missing something?

**Comment by czechboy0** [comment]
Hi @yaroslavyaroslav, you want to implement a custom ClientMiddleware and insert the header there, then pass the middleware to the Client initializer.

https://swiftpackageindex.com/apple/swift-openapi-runtime/0.3.6/documentation/openapiruntime/clientmiddleware

**Comment by yaroslavyaroslav** [comment]
Thanks for that hint, I believe I do, but is there some source where I can read more about the whole concept of this? As for now such layering is completely unclear for me and it goes against the logic that I saw in both client implementation tutorials that you have here. 

So I believe that without such broader context about the whole architecture design I'll stuck short after with some other misaligned usage of this tool.
