### ISSUE TITLE
Path Parameter Ordering

### ISSUE THREAD

**Issue by CraigLn** [apple/swift-openapi-generator#378]
I can't tell if this is an issue with how the OpenAPI is setup, but I cannot find anywhere it explicitly states that the `parameters` is required to be ordered.  

Here is the OpenAPI snippet:
```
"/config/settings/models/{model}/brands/{brand}/versions/{version}": {
    "get": {
        "parameters": [
            {
                "in": "path",
                "name": "version",
                "required": true,
                "schema": {
                    "type": "string"
                }
            },
            {
                "in": "path",
                "name": "model",
                "required": true,
                "schema": {
                    "type": "string"
                }
            },
            {
                "in": "path",
                "name": "brand",
                "required": true,
                "schema": {
                    "type": "string"
                }
            }
        ],
```

It contains three path parameters `model`, `brand`, and `version` ordered correctly within the path, but the `parameters` array field has them unordered with `version`, `model`, and `brand` with correct `name` fields matching those within the path. 

The generated Client code results is a an array which retains the order of the parameters list, but make to attempt to align based on the `name` key.
```
let path = try converter.renderedPath(
  template: "/config/settings/models/{}/brands/{}/versions/{}",
  parameters: [input.path.version, input.path.model, input.path.brand]
)
```

Is there a way I can generate the swift code to use a Dictionary instead of an array, or is the initial OpenAPI not to spec?

**Comment by czechboy0** [comment]
Thanks so much @CraigLn for filing this issue, it's indeed a bug that I'm preparing a fix for. 🙏

**Comment by czechboy0** [comment]
A temporary workaround would be to change your order of parameters to match the URL template's order. But a fix is incoming shortly.
