### ISSUE TITLE
 Deadlock at session.dataTask method on call

### ISSUE THREAD

**Issue by HonQii** [apple/swift-openapi-generator#388]
hi，When I use the generated code to send network requests, I found that if there are a large number of requests executing concurrently at the same time, it's easy to get stuck in a deadlock here at `configuration.session.dataTask(with: urlRequest)`, resulting in the request remaining unanswered. All my requests are initiated in the same thread and are executed in the same priority Task

Below is a screenshot of the stack of a thread call

<img width="586" alt="截屏2023-11-20 18 05 29" src="https://github.com/apple/swift-openapi-generator/assets/14954524/c4015666-4d8a-4a41-8460-14cbfd5b6c72">

**Comment by czechboy0** [comment]
Which release of swift-openapi-urlsession are you using? The main branch or a released version? cc @simonjbeaumont

**Comment by HonQii** [comment]
> Which release of swift-openapi-urlsession are you using? The main branch or a released version? cc @simonjbeaumont

0.3.0

**Comment by czechboy0** [comment]
Hmm the code is here then: https://github.com/apple/swift-openapi-urlsession/blob/2a676df437aeb50ddf8ecb0ad327d14f078d6cb6/Sources/OpenAPIURLSession/URLSessionTransport.swift#L109

The swift-openapi-urlsession code doesn't have any locks in there, so if the code is locking up, it must be an underlying URLSession issue. Maybe @guoye-zhang can help.

**Comment by guoye-zhang** [comment]
This appears to be Firebase swizzled URLSession, so I'm not sure if the lock is actually in URLSession:

https://github.com/firebase/firebase-ios-sdk/blob/854dad922c2fe0aad2436a2cd0f864224b569077/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m#L292

Would you share the thread state of all threads? Pause when the deadlock happens and run this in Xcode's lldb prompt:

```
command script import lldb.macosx.crashlog
save_crashlog /tmp/threads.txt
```

And attach the content of threads.txt here.

**Comment by czechboy0** [comment]
At this point, it might also make sense to move this issue to Firebase? If the generator or transport isn't at fault here, we might not be the best people to help debug this.

**Comment by HonQii** [comment]
> ```
> save_crashlog /tmp/threads.txt
> ```

[threads.txt](https://github.com/apple/swift-openapi-generator/files/13421301/threads.txt)

**Comment by guoye-zhang** [comment]
The deadlock appears to be in URLSession. However, I'm unable to find any obvious problems in our code, the code path looks perfectly safe.

I suspect that this is a bug in the app, exceptions thrown across Swift frames, or simply a memory corruption. Would you add an "exception breakpoint" in Xcode and run the app again? Also try ASAN / TSAN for potential memory bugs. If none of them catches any issues, I think we will need a reproducing project to investigate it further.

**Comment by HonQii** [comment]
> The deadlock appears to be in URLSession. However, I'm unable to find any obvious problems in our code, the code path looks perfectly safe.
> 
> I suspect that this is a bug in the app, exceptions thrown across Swift frames, or simply a memory corruption. Would you add an "exception breakpoint" in Xcode and run the app again? Also try ASAN / TSAN for potential memory bugs. If none of them catches any issues, I think we will need a reproducing project to investigate it further.

Okay, I'll debug it. I'll sync with you if I find anything.

**Comment by czechboy0** [comment]
Ok, closing the issue as the transport seems to be behaving correctly, and the issue seems to be in the swizzled Firebase version of URLSession.
