### ISSUE TITLE
Allow Xcode CMD+O to find code generated via OpenAPI Spec Generator

### ISSUE THREAD

**Issue by mapedd** [apple/swift-openapi-generator#397]
Hello amigos. I was wondering if it's possible to find symbols generated via native SPM OpenAPI gen plugin using Xcode's CMD+O panel? Doesn't seem to work for me on default.

**Comment by czechboy0** [comment]
Hi @mapedd - that sounds like a useful feature! But you'll need to file that on Xcode through http://feedbackassistant.apple.com.

**Comment by czechboy0** [comment]
It's because this is how Swift Package Manager build plugins work and how they're handled in Xcode. We have no control over that, unfortunately.
