### ISSUE TITLE
Use the same .swift-format in the repo and in the generated code

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#40]
We use swift-format both for formatting the generator code, and the generated code. However, the configuration is duplicated in both places, we should have one source of truth for it instead.

**Comment by denil-ct** [comment]
I've created a [PR](https://github.com/apple/swift-openapi-generator/pull/73) for this. Please have a look.

**Comment by czechboy0** [comment]
Well, this is good timing: https://github.com/apple/swift-package-manager/pull/6067

Unfortunately, it's only supported in Swift 5.9, so I propose we punt this issue until later, and adopt it when we bump the minimum tools version to 5.9.

**Comment by denil-ct** [comment]
Sounds good to me. So sometime in the fall when Xcode 15 comes out of beta I assume?

**Comment by czechboy0** [comment]
To be determined, but marking as blocked for now. You can close your other PR for now, but we'll definitely appreciate the contribution when Swift OpenAPI Generator requires Swift tools version 5.9!

**Comment by czechboy0** [comment]
Filed #75 to properly relate the two.

**Comment by denil-ct** [comment]
@czechboy0 if #75 is 1.0, can't this be under the same milestone as well?

**Comment by czechboy0** [comment]
@denil-ct the milestone doesn't mean when it'll land, it means which release it's blocking. It's likely this will land around the same time as #75, the milestone just means this wouldn't be considered a 1.0 blocker.

**Comment by czechboy0** [comment]
We don't use swift-format as a library anymore, so this is obsolete.
