### ISSUE TITLE
Regression: swift-openapi-runtime 0.3.6 requires explicit import of HTTPTypes when writing a ClientMiddleware.

### ISSUE THREAD

**Issue by robin24** [apple/swift-openapi-generator#406]
Summary:

Trying to write a ClientMiddleware for API key authentication, I ran into issues building my project due to Xcode not being able to find 'HTTPRequest' and 'HTTPResponse' in scope.

Steps to reproduce:

1. Create a new Xcode project and framework target for the APIClient.
2. Perform setup steps as described here: https://swiftpackageindex.com/apple/swift-openapi-generator/0.3.5/tutorials/swift-openapi-generator/clientxcode
3. In the target for the APIClient create a new file called AuthMiddleware.swift with the following code:
```
import OpenAPIRuntime
import OpenAPIURLSession

struct AuthMiddleware: ClientMiddleware {
    var apiKey: String
    func intercept(_ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String, next: (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)) async throws -> (HTTPResponse, HTTPBody?) {
        var request = request
        request.headerFields.append(
            .init(name: .init("X-API-KEY")!, value: apiKey))
        return try await next(request, body, baseURL)
    }
}
```

4. Try to build the project.

Expected results:
Project can be built without any errors.
Actual results:
Build fails due to HTTPRequest and HTTPResponse being out of scope, according to Xcode.
Workaround:
Importing HTTPTypes resolves the problem and results in Xcode being able to compile the project. However, seems like the need to import HTTPTypes isn't documented, so I assume this is likely a bug.
Regression info:
In an older project which uses swift-openapi-runtime 0.2.5, I was able to define a middleware without the need to import HTTPTypes.

System info:
OS: macOS Sonoma 14.2
`swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0`

**Comment by czechboy0** [comment]
Hi @robin24!

You're correct that 0.2.x didn't require an extra import, but in 0.3.x we adopted the ecosystem-wide solution to currency HTTP types in swift-http-types (https://github.com/apple/swift-http-types).

Needing to import it explicitly is expected behavior, just like you need to import other frameworks and package libraries.

We'll make sure that importing `HTTPTypes` explicitly is included in more examples for the repo that we're working on, and called out in the tutorials, thanks! cc @simonjbeaumont

**Comment by robin24** [comment]
Hey @czechboy0,

Thanks so much for the explanation, greatly appreciated!
Wasn't aware of this change and couldn't really find it documented (well possible that I just wasn't looking in the right place though), so figured this might have regressed somewhere.

Keep up the awesome work, this project has really gotten me interested in OpenAPI-related stuff and I really enjoy using it a lot! :-)

**Comment by czechboy0** [comment]
> this project has really gotten me interested in OpenAPI-related stuff and I really enjoy using it a lot! :-)

That's awesome to hear! OpenAPI really is great and we're excited to make it more accessible to the Swift community 🙂 

Now, about the breaking change, you're right that it was easy to miss.

It arrived in 0.3.0 (release notes: https://github.com/apple/swift-openapi-generator/releases/tag/0.3.0), which calls out that it has breaking changes, and only if you followed the link to the forums post you'd see the Migrating section: https://forums.swift.org/t/swift-openapi-generator-0-3-0-released-swift-http-types-streaming-bodies-shorthand-apis/67704#migrating-from-02x-to-030-6

It talks about now depending on Swift HTTP Types, but even there we don't explicitly call out needing to add an import for `HTTPTypes`, which is a good point. Thanks for taking the time to file this issue 🙏
