### ISSUE TITLE
Running swift-openapi-generator via CLI should not need a openapi-generator-config.yaml file

### ISSUE THREAD

**Issue by jbehrens94** [apple/swift-openapi-generator#407]
# Motivation
I tried to run the CLI tool via `swift run` only to find out I still need a `openapi-generator-config.yaml` file. I had not expected that, because what is the added value of passing it via the CLI if I need the config anyway? I would love to use the CLI without config file, so that I can generate the things I want/need in (for example) a Makefile.

# Proposal
Separate the CLI from the `openapi-generator-config.yaml` file, or at least let it be another option that doesn't mutually include each other.

**Comment by czechboy0** [comment]
Hi @jbehrens94, you're right - it shouldn't require a config file.

Are you talking about the error `Error: Must either provide a config file or specify --mode.`?

You can provide `--mode types --mode client`, for example, if generating a client, and the CLI invocation will not require you to have a config file.

Does that fix your issue?

**Comment by jbehrens94** [comment]
Hi @czechboy0, thanks for your blazing fast response! Let me elaborate about the options I've tried:

- Using the `swift run swift-openapi-generator` command without a configuration file present on disk. `swift run swift-openapi-generator generate openapi.yaml --mode types --mode client --output-directory ./`. *This does not work*
- Adding the configuration yaml file on disk with generate client and types, filter tag `basic`. `swift run swift-openapi-generator openapi.yaml generate openapi.yaml --mode types --mode client --output-directory ./` works, but outputs everything and doesn't filter.
- Using the `swift run swift-openapi-generator filter` command like described in the documentation doesn't seem to work, it's not available in `swift run swift-openapi-generator -help` command as a subcommand.

I'll explain my specific use case, maybe you've got an idea on what could work. I've got a huge OpenAPI yaml file, with about 12 tags. That would create huge PRs if I regenerate a part. Therefore, I would like to split up the generated code per tag. That way, I could even create a local package per tag and build more modular packages.

**Comment by czechboy0** [comment]
Thanks for the extra context. Okay, a few things here. (cc @simonjbeaumont as this is related to filtering)

> Using the swift run swift-openapi-generator command without a configuration file present on disk. swift run swift-openapi-generator generate openapi.yaml --mode types --mode client --output-directory ./. This does not work

That definitely should work, I just tried it on the `1.0.0-alpha.1` and it worked for me. Which tag are you using?

> Adding the configuration yaml file on disk with generate client and types, filter tag basic. swift run swift-openapi-generator openapi.yaml generate openapi.yaml --mode types --mode client --output-directory ./ works, but outputs everything and doesn't filter.

Here it seems you have the `openapi.yaml` argument before the `generate` command, that won't work.

Now, what you actually care about is this: filtering requires using the config file. Sorry, I didn't realize you wanted to use filtering before; we currently do not have CLI options for filters. Is that something you'd like to see? (If so, maybe we can repurpose this issue to track that.)

> Using the swift run swift-openapi-generator filter command like described in the documentation doesn't seem to work, it's not available in swift run swift-openapi-generator -help command as a subcommand.

I do see it there, maybe you're using an older version?

```
swift run swift-openapi-generator -help 
Building for debugging...
Build complete! (0.12s)
OVERVIEW: Generate Swift client and server code from an OpenAPI document

USAGE: swift-openapi-generator <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  filter                  Filter an OpenAPI document
  generate                Generate Swift files from an OpenAPI document

  See 'swift-openapi-generator help <subcommand>' for detailed help.
```

---

Having said all this, my read is that the thing you care about is doing filtering from the CLI, without a config file, is that accurate?

**Comment by jbehrens94** [comment]
I had not updated to `1.0.0-alpha.1`, I just tried that.

Given this folder (`/Users/jbehrens/Developer/<project>/API/Sources/API`):

```
ls -la
total 3944
drwxr-xr-x  6 jbehrens  staff      192 29 nov 22:42 .
drwxr-xr-x  3 jbehrens  staff       96 28 nov 20:56 ..
-rw-r--r--@ 1 jbehrens  staff      288 29 nov 21:32 API.swift
-rw-r--r--@ 1 jbehrens  staff   258522 29 nov 22:00 Client.swift
-rw-r--r--@ 1 jbehrens  staff  1531323 29 nov 22:42 Types.swift
-rw-r--r--  1 jbehrens  staff   220642 28 nov 20:56 openapi.yaml
```

The output is this:
```
swift run swift-openapi-generator generate openapi.yaml --mode types --mode client --output-directory ./
warning: 'api': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/jbehrens/Developer/<project>/API/Sources/API/openapi.yaml
Building for debugging...
Build complete! (0.38s)
error: Issues with required files: No config file found in the target named 'API'. Add a file called 'openapi-generator-config.yaml' or 'openapi-generator-config.yml' to the target's source directory. See documentation for details..
error: build stopped due to build-tool plugin failures
warning: 'api': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/jbehrens/Developer/<project>/API/Sources/API/openapi.yaml
Building for debugging...
Build complete! (0.38s)
error: Issues with required files: No config file found in the target named 'API'. Add a file called 'openapi-generator-config.yaml' or 'openapi-generator-config.yml' to the target's source directory. See documentation for details..
error: build stopped due to build-tool plugin failures
```

I do indeed care about filtering from the CLI, so I can check in separate files or split them into several packages. That's the goal. :)

**Comment by jbehrens94** [comment]
Also, running `swift run swift-openapi-generator --help` results in:

```
swift run swift-openapi-generator --help
warning: 'api': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/jbehrens/Developer/<project>/API/Sources/API/openapi.yaml
Building for debugging...
Build complete! (0.38s)
error: Issues with required files: No config file found in the target named 'API'. Add a file called 'openapi-generator-config.yaml' or 'openapi-generator-config.yml' to the target's source directory. See documentation for details..
error: build stopped due to build-tool plugin failures
warning: 'api': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/jbehrens/Developer/<project>/API/Sources/API/openapi.yaml
Building for debugging...
Build complete! (0.39s)
error: Issues with required files: No config file found in the target named 'API'. Add a file called 'openapi-generator-config.yaml' or 'openapi-generator-config.yml' to the target's source directory. See documentation for details..
error: build stopped due to build-tool plugin failures
```

**Comment by jbehrens94** [comment]
Alright, I forgot to remove the plugin from Package.swift for option 2 and/or 3. One of method 2 or 3 would work for me, I'm not really hung on any of the two.

From what I understand from the CLI help, the `filter` command will output the correct YAML configuration for the filters. That's not what I am looking for, I want the filter to be applied on the output of the CLI tool. So, if I want only the operations etc. for tag `basic`, I don't want the other stuff there.

I'm not sure if I am explaining my needs well enough, if so, I can give another example.

**Comment by czechboy0** [comment]
I think I understand. The filter command is only used as a way to test out your `filter` part of the configuration file. Once you have the right config file, e.g.

```
generate:
- types
- client
filter:
  tags:
    - foo
    - bar
```

you would use the plugin or the CLI to generate the code. The generator will first filter down to only your requested content, and then generated the code for it. I _think_ that's what you want?

Check out the docs on filtering here: https://swiftpackageindex.com/apple/swift-openapi-generator/0.3.5/documentation/swift-openapi-generator/configuring-the-generator#Document-filtering

**Comment by simonjbeaumont** [comment]
OK, there are two issues here, which I summarise as (details to follow):

1. Running `swift run swift-openapi-generator` _from an adopter package_ isn't something we've expected (it is being interpreted as a plugin invocation).
2. Filtering requires a config file.

---

### Details on running `swift-openapi-generator` "from the CLI". 

Right, I think the core difference here is "running swift-openapi-generator from the CLI" can mean one of three things:
1. Running `swift-openapi-generator`, the binary, directly, from some precompiled version.
2. Running `swift run swift-openapi-generator` from a checkout of `swift-openapi-generator`.
3. Running `swift package generate-code-from-openapi` using the command plugin from your package.

(1) is equivalent to (2) and both of these should work just fine without a config file.

(3) is invoking the generator as a Swift package command plugin.

What you're doing is something I didn't think was even possible:

4. Running `swift run swift-openapi-generator` from your own package, that depends on `swift-openapi-generator`.

I just tried it and was surprised/confused as I thought that `swift run` would only allow you to run executable targets in your own package. However, I can confirm I tried it and `swift run swift-openapi-generator` does indeed try and run the generator and I can confirm that it has the limitations you see.

Specifically, if I take the `IntegrationTest` directory, which is a package that depends on `swift-openapi-generator` like an adopter package would... In this environment, I can run the following command with no problems:

```console
❯ swift run swift-openapi-generator --help
...
Build complete! (1.65s)
OVERVIEW: Generate Swift client and server code from an OpenAPI document
...
```

Additionally I can use the `generate` subcommand:

```console
❯ swift run swift-openapi-generator generate --mode types Sources/Types/openapi.yaml
Building for debugging...
Build complete! (0.12s)
Swift OpenAPI Generator is running with the following configuration:
- OpenAPI document path: /Users/Si/work/code/swift-openapi-workspace/packages/IntegrationTest/Sources/Types/openapi.yaml
- Configuration path: <none>
- Generator modes: types
- Feature flags: <none>
- Output file names: Types.swift
- Output directory: /Users/Si/work/code/swift-openapi-workspace/packages/IntegrationTest
- Diagnostics output path: <none - logs to stderr>
- Current directory: /Users/Si/work/code/swift-openapi-workspace/packages/IntegrationTest
- Plugin source: <none>
- Is dry run: false
- Additional imports: <none>
Writing data to file Types.swift...
```

This is a strange hybrid mode... From the logs, we can see that it has written `Types.swift` to the current working directory, but also made use of the config file that was next to the `openapi.yaml`.

However, I can confirm, that if we remove the config file thats sitting next to the `openapi.yaml` passed, I can reproduce the behaviour that it cannot be run without the config file...

```console
❯ rm Sources/Types/openapi-generator-config.yaml

❯ swift run swift-openapi-generator generate --mode types Sources/Types/openapi.yaml
...
error: Issues with required files: No config file found in the target named 'Types'. Add a file called 'openapi-generator-config.yaml' or 'openapi-generator-config.yml' to the target's source directory. See documentation for details..
error: build stopped due to build-tool plugin failures
```

I think what's happening here is that the tool thinks it's being invoked as a plugin. When it's invoked as a plugin, it _must_ have a config file.

I think the confusion here is that running `swift run swift-openapi-generator` form an package that _depends_ on `swift-openapi-generator` (cf. `swift-openapi-generator` repo itself) results in SwiftPM executing this in a way that we (inside `swift-openapi-generator`) perceive to be a plugin invocation.

This is something we can investigate.

---

### Running the `swift-openapi-generator` as a CLI (the way we support today)

You will need to run it in either way (1) or (2) above. Here's an example showing that it's possible to run the generator without a config file just fine with the `generate` subcommand. Note that it uses `<none>` config file and still writes the file.

```console
❯ swift run --package-path /path/to/swift-openapi-generator-checkout swift-openapi-generator generate --mode types Sources/Types/openapi.yaml
...
Swift OpenAPI Generator is running with the following configuration:
- OpenAPI document path: /Users/Si/work/code/swift-openapi-workspace/packages/IntegrationTest/Sources/Types/openapi.yaml
- Configuration path: <none>
- Generator modes: types
- Feature flags: <none>
- Output file names: Types.swift
- Output directory: /Users/Si/work/code/swift-openapi-workspace/packages/IntegrationTest
- Diagnostics output path: <none - logs to stderr>
- Current directory: /Users/Si/work/code/swift-openapi-workspace/packages/IntegrationTest
- Plugin source: <none>
- Is dry run: false
- Additional imports: <none>
Writing data to file Types.swift...
```

### Running `swift-openapi-generator filter`

You should be able to perform filtering in a similar manner. However, as you noted, this _does_ require a config file to express the filters you want to apply.

```console
❯ cat filter-config.yaml
generate: []
filter:
  schemas:
    - Greeting

❯ swift run --package-path /path/to/swift-openapi-generator-checkout swift-openapi-generator filter --config filter-config.yaml Sources/Types/openapi.yaml
Parsing document...
Parsing document complete! (0.00s)
Filtering document...
Filtering document complete! (0.00s)
openapi: 3.1.0
info:
  title: GreetingService
  version: 1.0.0
servers:
- url: https://example.com/api
  description: Example
components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string
      required:
      - message
```

Does this help?

**Comment by simonjbeaumont** [comment]
Heh, in the time it took me to compose the above, I see there were more updates. 😅 

As @czechboy0 said, you can use `filter:` in the config file when using `generate` subcommand or when using the plugin workflow.  But you cannot provide filtering options on the command line when using the `generate` subcommand.

The `filter` subcommand is designed as OpenAPI document in, OpenAPI document out. For both debugging, and preprocessing.

**Comment by jbehrens94** [comment]
I tried the symlinking before, but that causes Xcode to completely freeze on my end.

**Comment by simonjbeaumont** [comment]
> I tried the symlinking before, but that causes Xcode to completely freeze on my end.

That should not be the case. I'm curious about this, though; could you try cloning this repo and opening the `IntegrationTest/` directory in Xcode (do not open the root package). It makes use of symlinks for the`openapi.yaml` all over.

I am able to open it fine on the most recent Xcode (15.0.1).

**Comment by jbehrens94** [comment]
I don't know what it is with me, but in the past it didn't work and now it does. I used the symlinking approach to generate the `GeneratedSources` folder per package.

Like this:

```bash
for folder in *API; do cd "$folder" && swift package plugin generate-code-from-openapi --target "$folder" && cd ..; done
```

However, I seem to get errors because the generator plugin also generates the code under the hood of course. Am I using this as intended?

**Comment by czechboy0** [comment]
You should use _either_ the command plugin (`swift package plugin generate-code-from-openapi --target ...` which emits the code into your git repo, and you check that in, in which case you only include the generator as a package dependency, but you do _not_ add it into the `plugins` section for your target), or as the build plugin (recommended, you add the generator as a package dependency and add it to the `plugins` section for your target, this way the code is generated during the build and is _not_ checked into your git repo).

Which one would you like to use?

**Comment by jbehrens94** [comment]
Sorry for my late response! 

It was the first, but I didn't realise I could keep the dependency and remove the plugin, so I think I got there! Thank you both so much for your help, much appreciated.
