### ISSUE TITLE
Replace dynamic type checks with generic overloads

### ISSUE THREAD

**Issue by simonjbeaumont** [apple/swift-openapi-generator#41]
A recent PR to the runtime library was fixing an issue for the transcoding of types that have an additional protocol conformance. This was done with a dynamic `as?` type check and an `as!` force cast.

In a comment, we discussed a better way: using a specialization and letting the compiler do the work: https://github.com/apple/swift-openapi-runtime/pull/9#discussion_r1206952776.

We approved the PR as-was because it matched the pattern we were using in the rest of the code base and was a targeted fix for an issue.

This issue is to track revisiting the dynamic type checking pattern in all the places its used in the runtime library and adopting the pattern in the linked PR comment.

**Comment by czechboy0** [comment]
This is addressed in the latest solution to #43.
