### ISSUE TITLE
Decl has a package access level but no -package-name was passed when used directly in App target

### ISSUE THREAD

**Issue by erikhric** [apple/swift-openapi-generator#425]
The following error is occuring when using in App target directly:
`Decl has a package access level but no -package-name was passed` <br>
No error is thown when used in package tho.

**Comment by czechboy0** [comment]
Yes, I also just saw it today in an app target.

The workaround is to add `accessModifier: internal` (or `public`) to the config file.

Let's use this issue to track at the very least documenting this (hopefully temporary) issue.

**Comment by czechboy0** [comment]
> I'd also like to suggest updating the announcement post

Good idea, updated 👍

**Comment by czechboy0** [comment]
Resolution: switched the default to `internal` and documented what to do in case someone hits this error in the new FAQ page. Closing.
