### ISSUE TITLE
URLSession transport threw an error

### ISSUE THREAD

**Issue by QZone99** [apple/swift-openapi-generator#430]
I got the following error by using `1.0.0-alpha.1`.

```
Client error - cause description: 'Transport threw an error.', underlying error: cancelled
```

It was working fine before with the following versions:

swift-openapi-generator -> 0.3.5
swift-openapi-runtime -> 0.3.6
swift-openapi-urlsession -> 0.3.0

My investigations show that upgrading the swift-openapi-urlsession to 0.3.1 from 0.3.0 generates the same error as well.

**Comment by czechboy0** [comment]
Did you try with all 3 packages using `1.0.0-alpha.1`?

Which platform is this on? What sort of HTTP request is this?

cc @simonjbeaumont

**Comment by simonjbeaumont** [comment]
I wonder if this hit a redirect, but we need a bit more information to understand the failure mode. 


Depending on the platform and the HTTPBody iteration behaviour, a HTTP redirect could cause the URLSession task to be cancelled if the body cannot be iterated multiple times.

Do you have some more details to help us triage this issue?

**Comment by QZone99** [comment]
Encountering the issue on macOS with `URLSessionTransport` in the `Client` while executing a GET HTTP request with no `requestBody`, only `parameters`. Unsure whether the GET request is reaching the redirect. Postman tests show a successful 200 OK response.

The problem surfaced after updating the package version of `swift-openapi-urlsession` from `0.3.0` to `0.3.1`. Testing with version `1.0.0-alpha.1` for all three packages resulted in the same error.

Previously functional versions:

swift-openapi-generator -> 0.3.5
swift-openapi-runtime -> 0.3.6
swift-openapi-urlsession -> 0.3.0

**Comment by QZone99** [comment]
```
% sw_vers
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B92
```
```
public struct MyService<C: APIProtocol> {
    let client: C
    
    public init(client: C) { self.client = client }
    
    public init() where C == Client {
        self.client = Client(
            serverURL: try! Servers.server1(),
            transport: URLSessionTransport()
        )
    }

    public func name(_ id: String) async throws {
        let response = try await client.name(
            Operations.options.Input(
                path: Operations.options.Input.Path(
                    id: id
                )
            )
        )
        switch response {
        case let .ok(okResponse):
            switch okResponse.body {
            case .json(let json):
                print(json)
            }
        case .undocumented(statusCode: let statusCode, _):
            print(statusCode)
        }
    }
}
```
```
Task {
    let service = MyService()
    do {
       async let _ = service.name(id)
       async let _ = service1.other(id)
     } catch { 
       print(error)
     }
}
```


I found that it is working when using `await`
```
Task {
    let _ = await service.name(id)
}
```
But not when using `async let`
```
Task {
    async let _ = service.name(id)
    async let _ = service1.other(id)
}
```

I have multiple requests need to send (all of them using the same techniques describe above), and would like to send them in parallel, that is why I use `async let`.
