### ISSUE TITLE
Unable to Set 'Add to Target' to 'None' for Swift OpenAPI Generator Package in Xcode

### ISSUE THREAD

**Issue by TweedBeetle** [apple/swift-openapi-generator#493]
#### Environment:
- Xcode Version: 15.1 (15C65)
- Swift OpenAPI Generator Version: [Specify the version, if known]

#### Issue Description:
I am attempting to add the Swift OpenAPI Generator package to my Xcode project following the instructions provided in the documentation. However, I'm facing an issue at the step where I need to ensure that the 'Add to Target' value is set to 'None' for the Swift OpenAPI Generator build plugin.

According to the [instructions](https://swiftpackageindex.com/apple/swift-openapi-generator/1.0.0/tutorials/swift-openapi-generator/clientxcode), since this package is a build plugin, it should not be added to a specific target at this stage. Instead, it will be integrated into the build process later. However, in the Xcode UI, I cannot proceed without selecting a target—the 'Add Package' button becomes greyed out when I set the project to 'None'.

#### Steps to Reproduce:
1. Open the Xcode project and navigate to 'Package Dependencies'.
2. Click the plus button to add a new package dependency.
3. Type the [repo url](https://github.com/apple/swift-openapi-generator) in the search field and select the package
4. On the 'Choose Package Products' screen, attempt to set 'Add to Target' to 'None'.

#### Expected Behavior:
I should be able to set 'Add to Target' to 'None' for the Swift OpenAPI Generator package and proceed with the integration.

#### Actual Behavior:
The 'Add Package' button is greyed out when 'Add to Target' is set to 'None', preventing me from adding the package without associating it with a target.

<img width="1084" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/12238004/0b1274a6-4dec-47ae-a6fd-67210b5c90b7">

Could anyone provide guidance on how to correctly add the Swift OpenAPI Generator as a build plugin without setting a target?

I would appreciate any help or insights the community can offer on this matter. Thank you in advance!

**Comment by czechboy0** [comment]
It's okay to set "Add to Project" to your project. The "Add to Target" picker is later, after you click "Add Package".

**Comment by TweedBeetle** [comment]
> It's okay to set "Add to Project" to your project. The "Add to Target" picker is later, after you click "Add Package".

Ah, duh 🤦‍♂️

Thank you!
