### ISSUE TITLE
Make Input/Output (and nested) types Equatable/Hashable

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#5]
We should make the generated operation-specific Input/Output (and nested) types Equatable.

A few drivers:
- easier testing
- easier caching of hash(Input) -> cached Output
- more consistent with most of the other generated types

**Comment by glbrntt** [comment]
@czechboy0 unless I'm missing something this appears to already be done:

- https://github.com/apple/swift-openapi-generator/blob/3b128349cb337b7f3dc5ca01277208160283a6f2/Sources/_OpenAPIGeneratorCore/Translator/CommonTypes/Constants.swift#L225
- https://github.com/apple/swift-openapi-generator/blob/3b128349cb337b7f3dc5ca01277208160283a6f2/Sources/_OpenAPIGeneratorCore/Translator/CommonTypes/Constants.swift#L238

**Comment by czechboy0** [comment]
Already done.
