### ISSUE TITLE
Issue with paths ending with a slash

### ISSUE THREAD

**Issue by miguel-arrf** [apple/swift-openapi-generator#51]
**Context:**
Hi! I was testing creating a Client with the following `openapi.yaml` file:

```
openapi: 3.0.2
info:
  title: FastAPI
  description: Example app
  version: 0.1.0
servers:
  - url: http://127.0.0.1:8000
    description: Localhost deployment.
paths:
  /items/:
    get:
      tags:
        - Items
      summary: Read Items
      operationId: read_items_items__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Read Items Items  Get
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      tags:
        - Items
      summary: Create Item
      operationId: create_item_items__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    Item:
      title: Item
      required:
        - name
        - price
      type: object
      properties:
        name:
          title: Name
          type: string
        description:
          title: Description
          type: string
        price:
          title: Price
          type: number
        tax:
          title: Tax
          type: number
        tags:
          title: Tags
          type: array
          items:
            type: string
          default: []
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string

```

Here's my `main.swift` (this is for a Swift Package):

```
import OpenAPIRuntime
import OpenAPIURLSession

let client = Client(
    serverURL: try Servers.server1(),
    transport: URLSessionTransport()
)

let response = try await client.read_items_items__get(
    .init()
)


switch response {
case .ok(let okResponse):
    switch okResponse.body {
    case .json(let greeting):
        print(greeting)
    }
case .undocumented(statusCode: let statusCode, _):
    print("🥺 undocumented response: \(statusCode)")
}

```

If I inspect the generated file for the `Client`, here's part of the code:

```
public func read_items_items__get(_ input: Operations.read_items_items__get.Input) async throws
        -> Operations.read_items_items__get.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.read_items_items__get.id,
            serializer: { input in
                var request: OpenAPIRuntime.Request = .init(path: "/items", method: .get)
(...)
```

**Shouldn't the path be `/items/` instead of `/items`?**

In my specific use case, my server is a FastAPI server, and this is what I get when I run the package (with command: `swift run --package-path Swift-With-FastAPI-Package`):
```
127.0.0.1:63403 - "GET /items HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:63403 - "GET /items/ HTTP/1.1" 200 OK
```

The output of the `swift run (...)` command is the expected, however I would like to avoid the redirect in the Server. **Is this the expected behaviour?**

---

$ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

Operating system: macOS 13.2

$ uname -a
Darwin XPQFF7Q9JC 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:50:21 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8112 arm64

**Comment by czechboy0** [comment]
Hi @miguel-arrf, thank you for taking the time to file this _great_ issue 👏

Just recently, @simonjbeaumont and I discussed this behavior, so I suspect it is a bug on the generator currently. We'll have to investigate where exactly the trailing slash gets stripped and figure it out from there. If you're able to, you could debug the generator yourself – which is probably easiest by cloning the repo, opening it in your IDE, and launching the CLI target with a debugger attached. We have more docs on [contributing](https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.0/documentation/swift-openapi-generator/manually-invoking-the-generator-cli) here. A good first breakpoint might be around here: https://github.com/apple/swift-openapi-generator/blob/main/Sources/_OpenAPIGeneratorCore/Translator/Operations/OperationDescription.swift#L240, where the path is parsed from the OpenAPI doc and used to generate the client code.

Now, as a temporary workaround, you could implement a [`ClientMiddleware`](https://swiftpackageindex.com/apple/swift-openapi-runtime/0.1.0/documentation/openapiruntime/clientmiddleware) that, for a set of known operation ids modifies the [`path`](https://swiftpackageindex.com/apple/swift-openapi-runtime/0.1.0/documentation/openapiruntime/request/path) to add the trailing slash before it goes out to the transport and gets sent out. That should allow you to get rid of the redirect. Once the generator is fixed, you'll be able to delete this middleware.

**Comment by czechboy0** [comment]
It's possible that the trailing slash is getting stripped in OpenAPIKit – @mattpolzin have you seen this before?

**Comment by miguel-arrf** [comment]
Hi! 

Yup, it's exactly there that it is happening!

So, basically the _issue_ was starting [here](https://github.com/apple/swift-openapi-generator/blob/02924d14e50abe750a6bd194f2d652d0bd7ad60d/Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift#L62) when decoding the data with the `OpenAPI.Document.self` object.

My first guess was try to use the JSONDecoder instead of the YAMLDecoder, but the issue remained. I was then able to figure out where the issue is coming from. It's coming from the Path struct from OpenAPIKit, see [here](https://github.com/mattpolzin/OpenAPIKit/blob/d3c27d8fc488a97aef9a3a6a39c1b443900c866f/Sources/OpenAPIKit/Path%20Item/PathItem.swift#L20). What's happening is that they are spliting the path components by the `/` separator, meaning that all trailing `/` are getting ignored. 

They mention the OpenAPI specification (available [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#paths-object)). Upon reading it, I'm not entirely sure that the correct behaviour is to eliminate the last `/` from a Path if there are no components after it. With this, on the specification there are no cases of any endpoint ending up with a `/`, so I'm assuming they aren't expecting any trailing `/` to appear.

I will open an issue with OpenAPIKit to try to figure out what can be done! :)

Thank you so much for the help! @czechboy0

**Comment by mattpolzin** [comment]
I've not heard about this problem before, but looking at the OpenAPIKit source i can confirm the problem is in how it handles these paths (splitting on forward-slash and then joining back with slash to create a string representation). 

So, the bug was born of an oversight on my part. I'm on vacation without a laptop for the next week but after that I can fix the problem upstream in OpenAPIKit (especially if someone is kind enough to create me a GitHub issue to track this bug).

**Comment by simonjbeaumont** [comment]
Thanks @miguel-arrf for taking the time to dive into this one and thanks @mattpolzin for offering to take a look at a fix in OpenAPIKit—please feel free to link an issue here and we'll be more than happy to to integrate it when its ready.

**Comment by mattpolzin** [comment]
This issue has been fixed for OpenAPIKit releases `2.5.2` and `3.0.0-alpha.7`.

Thanks all for raising and investigating this!

**Comment by czechboy0** [comment]
Thanks @mattpolzin for the fix!

@miguel-arrf, do you want to do the honors of opening a PR bumping our dependency to alpha 7?

**Comment by miguel-arrf** [comment]
Hi! 

Thank you all so much for the help @czechboy0 @mattpolzin @simonjbeaumont 

I had a fix implemented in my local repository, but it was a bit less elegant 😅!

I'm on vacations and unfortunately I have limited internet connection!

If it is okay by you @czechboy0 , I will gladly open the PR in the next (more or less) 12 hours 🙂. 

Thank you for the opportunity and all the help!!

**Comment by mattpolzin** [comment]
> it'd be good to be confident in the fix.

Shots fired. 😄 totally kidding, 100% same page about testing philosophy.

**Comment by czechboy0** [comment]
> > it'd be good to be confident in the fix.
> 
> Shots fired. 😄 totally kidding, 100% same page about testing philosophy. 

Haha, I meant that we correctly integrate the fix 😉 No shade intended.
