### ISSUE TITLE
Instance method 'getResponseBodyAsJSON(_:from:transforming:)' requires that 'HTTPBody' conform to 'Decodable'

### ISSUE THREAD

**Issue by ForestKatsch** [apple/swift-openapi-generator#511]
### Description

I created a new Framework project in Xcode, then set up `swift-openapi-generator`, `swift-openapi-runtime`, and `swift-openapi-urlsession` as [described here](https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.9/tutorials/swift-openapi-generator/clientxcode), save for using Jellyfin's OpenAPI document [as found here](https://api.jellyfin.org/) (warning: huge page, takes a bit to load.)

When I build the project, I get this error:

```
Instance method 'getResponseBodyAsJSON(_:from:transforming:)' requires that 'HTTPBody' conform to 'Decodable'
```

on line 3,975 and 28,168 of `Client.swift`.

### Reproduction

1. Checkout the [reproduction project](https://github.com/ForestKatsch/ReproJellyfinOpenAPI)
2. Open in Xcode and build

### Package version(s)

`swift-openapi-generator`: 1.2.0
`swift-openapi-runtime`: 1.3.2
`swift-openapi-urlsession`: 1.0.1

### Expected behavior

I expected the generated code to compile without errors.

### Environment

Swift
```
$ swift --version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
$
```

macOS Sonoma 14.2.1
![Screenshot 2024-01-19 at 7 32 55 PM](https://github.com/apple/swift-openapi-generator/assets/42914657/d412725d-0be8-49fd-8984-4331d3e12312)

Xcode 15.2
![Screenshot 2024-01-19 at 7 32 40 PM](https://github.com/apple/swift-openapi-generator/assets/42914657/5f9078d0-791b-4b60-9079-220089d8c254)

**Comment by czechboy0** [comment]
I can't verify this right now, but my first hunch is that it's caused by a bug in the OpenAPI document: using the application/json content type with a schema of type string and format binary.

That's not allowed. The body either has to be JSON, or raw binary data, but not both.

If you let me know which is desired, I can advise how to update the OpenAPI document.

**Comment by ForestKatsch** [comment]
That was exactly it, thank you!

![Screenshot 2024-01-20 at 9 41 33 AM](https://github.com/apple/swift-openapi-generator/assets/42914657/5404e508-42f5-4a46-aa39-0cfa52526928)

I haven't dug much into OpenAPI, but are there any guides you'd recommend that would have helped me solve this myself?

**Comment by czechboy0** [comment]
Any stricter OpenAPI linter/validator should catch this, I think.
