### ISSUE TITLE
registerHandlers should throw an error if serverURL doesn't match documentation

### ISSUE THREAD

**Issue by ladiesman218** [apple/swift-openapi-generator#528]
### Motivation

In 
```swift
@main struct HelloWorldVaporServer {
    static func main() async throws {
        let app = Vapor.Application()

        let transport = VaporTransport(routesBuilder: app)
        let handler = Handler()
        try handler.registerHandlers(on: transport, serverURL: URL(string: "/api")!)
        try await app.execute()
    }
}

```

If I made a typo in `serverURL` parameter, I can use the mis-typed url instead of the one defined in `openapi.yaml` file. Is it better to throw an error if this happens?
Say for example in my `openapi.yaml` file, I have 
```lml
servers:
  - url: https://example.com/api
```
But in the above function I typed `/aoi`, I could still use `127.0.0.1:8080/aoi` to access the endpoint instead of getting an error.

### Proposed solution

Throw error if this happens

**Comment by czechboy0** [comment]
Hi @ladiesman218,

if you have a server defined in the OpenAPI document, you can use it from Swift code as follows:

```swift
try handler.registerHandlers(on: transport, serverURL: Servers.server1())
```

Only pass in a manually constructed URL if you need to provide a server URL not defined in the OpenAPI document.

Does that help?

**Comment by ladiesman218** [comment]
Definitely. Thx 
I was following this tutorial https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.0/tutorials/swift-openapi-generator/adding-openapi-and-swagger-ui-endpoints and made a typo in the url parameter, spent some time to track it down😂

Will close this
