### ISSUE TITLE
Issue Enabling OpenAPIGenerator Plugin for Xcode Cloud Build

### ISSUE THREAD

**Issue by TweedBeetle** [apple/swift-openapi-generator#531]
### Question

I am encountering an issue when trying to use the OpenAPIGenerator plugin during an Xcode Cloud build process. Despite following the setup instructions, I'm facing a problem with enabling the plugin for my project, which is preventing my builds from succeeding.

**Environment**:
- macOS Version: Sonoma 14.3.1 (23D60)
- Xcode Version: 15.2 (15C500b)
- Swift OpenAPI Generator Version: 1.0.0

**Issue Description**:
During the Xcode Cloud build process, I receive an error stating that the "OpenAPIGenerator must be enabled before it can be used" and that "OpenAPIGenerator is disabled." This issue occurs at the stage where my project attempts to archive using the `xcodebuild archive` command.

**Error Message**:
<img width="545" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/12238004/955ced64-5795-48fd-af75-273e79f185de">

Could you please provide guidance on how to properly enable the OpenAPIGenerator plugin for use in Xcode Cloud builds? Any advice or steps that I might be missing would be greatly appreciated.

Thank you for your support and for developing such a useful tool.

Best

**Comment by simonjbeaumont** [comment]
Hey @TweedBeetle. That's a known thing with Xcode Cloud. The workaround is here: https://developer.apple.com/forums/thread/732893. 

If that doesn't work, please reopen and we'll take a closer look.
