### ISSUE TITLE
Expose internal symbols

### ISSUE THREAD

**Issue by mapedd** [apple/swift-openapi-generator#533]
### Question

I  have a SPM target that uses OpenAPI Swift generator to generate client code, it's called `APIInteractor`
I'd  like to use this module in my tests, `APIIntegrationTests` but I can't find a way to use any type that's generated, such as (in my example) `Components.Schemas.EventId`. 

All those types are marked `internal` as they are code generated using a spm plugin. Is it possible to expose them to test target?

Something like this does not help:

```
public typealias ProductId = Components.Schemas.ProductId
```
I'm getting:
```
Type alias cannot be declared public because its underlying type uses an internal type
```

Edit:
I know this can be done if I invoke the code gen manually , but spm plugins are so awesome :)

**Comment by mapedd** [comment]
yup, that was it

**Comment by mapedd** [comment]
example config file for this to work:

```
generate:
  - types
  - client
accessModifier: public
```

**Comment by simonjbeaumont** [comment]
@mapedd just to clear this up for others, IIUC, you could have achieved this with package, instead of public and not risk leaking these types through your public API. 

Another option is to use `@testable import` in your tests.
