### ISSUE TITLE
Parsing ISO8601 date time from server fails due to milliseconds

### ISSUE THREAD

**Issue by laurensvm** [apple/swift-openapi-generator#537]
### Question

The server returns date-time strings as `2023-12-28T11:08:38.303+01:00`. The default `JSONDecoder` does not parse this properly and an extension is required to fallback to millisecond parsing. 
I'm wondering what in your opinion is the best way to solve this issue (preferably without changing the openapi spec, as many other services rely on it. I know it would be possible to parse it as a string and convert to `Date` manually, but this would require changing the openapi spec).
Is it possible to provide a custom `JSONDecoder` to the generator with a `DateFormatter` able to handle the millisecond ISO8601 date-time? 

Thanks a lot for this project and your help!

**Comment by simonjbeaumont** [comment]
@laurensvm `Client.init` accepts a `configuration: OpenAPIRuntime.Configuration` parameter. This allows you to specify a different (or custom) `DateTranscoder`.

By default, this is `DateTranscoder.iso8601` which uses Foundation's default settings, which, as you point out, do not handle fractional seconds. 

You can use `.iso8601WithFractionalSeconds` instead, which does handle this:

```swift
let client = Client(
    serverURL: URL(string: "http://localhost:8080/api")!,
    configuration: .init(dateTranscoder: .iso8601WithFractionalSeconds),  // <-- Specify the date transcoder here.
    transport: URLSessionTransport()
)
```

**Comment by laurensvm** [comment]
Thank you, this is exactly what I was looking for!
