### ISSUE TITLE
Add a CI pipeline for catching API-breaking changes

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#54]

**Comment by simonjbeaumont** [comment]
We have a tight dependency on the packages in the Swift OpenAPI project, which are part of different repositories. Most notably we have the interplay between `swift-openapi-generator` and `swift-openapi-runtime`. The latter vends SPI that's used in the generated code.

We'd like to be able to use the integration test package in this repo to test changes made in this repo and the runtime repo.

Additionally we may wish to consider using `swift package diagnose-api-breaking-changes` in the pipeline of the runtime library.

**Comment by simonjbeaumont** [comment]
> We'd like to be able to use the integration test package in this repo to test changes made in this repo and the runtime repo.

Here's the PR for the generator: https://github.com/apple/swift-openapi-generator/pull/56

**Comment by simonjbeaumont** [comment]
Here's the PR for the runtime: https://github.com/apple/swift-openapi-runtime/pull/17

**Comment by czechboy0** [comment]
@simonjbeaumont Ready to close this?

**Comment by czechboy0** [comment]
Since the integration test was added to CI, renaming to track adding the diagnosis of API-breaking changes to the runtime repo.

**Comment by simonjbeaumont** [comment]
> Since the integration test was added to CI, renaming to track adding the diagnosis of API-breaking changes to the runtime repo.

Done: https://github.com/apple/swift-openapi-runtime/pull/21.

I think we'll want to add an API breaking change to the generated code, but I think that's beyond the scope of this issue, so I'm closing this one now.
