### ISSUE TITLE
Streamlining Use

### ISSUE THREAD

**Issue by JetForMe** [apple/swift-openapi-generator#542]
### Motivation

Migrating from writing Swift Vapor controllers directly to using Open API, I've found the latter to be substantially more cumbersome. A simple POST handler in Vapor might look like this:

```swift
func registerAPNDevice(req inReq: Request)  async throws -> HTTPStatus {
    let req = try inReq.content.decode(RegisterAPNRequest.self)
    print("DeviceID: \(req.deviceID)")
    return .created
}
```

To my novice use of the generated code, I have to write this:

```swift
func registerAPNDevice(_ inInput: Operations.registerAPNDevice.Input) async throws -> Operations.registerAPNDevice.Output {
    guard
        case let .json(json) = inInput.body,
        let deviceIDs = json.deviceID,
        let deviceID = UUID(uuidString: deviceIDs)
    else
    {
        throw Abort(.badRequest)
    }
    
    print("DeviceID: \(deviceID)")
    
    return .created(.init())
}
```

Additionally, it took me far too long to figure out how to write this code. Xcode’s code completion rarely works reliably for me, which didn’t help. But I spent a lot of time just trying to drill down through the hierarchy of data structures to get at the data I needed (the request content).

The client side isn't much better:

```swift
try await client.registerAPNDevice(body: .json(.init(deviceId: "foo")))
```

This exposes in the client the internal structure of the request (JSON in the body). It would be better to have Swift struct as an abstraction that one hands to the generated code, which is responsible for packaging it and sending it to the server. 

I was directed to this [example](https://github.com/apple/swift-openapi-generator/blob/main/Examples/various-content-types-server-example/Sources/ContentTypesServer/ContentTypesServer.swift) recently, but honestly it doesn't feel any better. The code is littered with boilerplate (lots of `.init()`, for example).

### Proposed solution

The generator should generate additional accessor functions to streamline access to the values. I'm not really sure exactly what the form of this should take is, but the `Input` object should have methods or properties that let me get directly at the content I want. Don't make my handler dig through the HTTP structure to get at it. Similarly for the client side, don't make the code expose the HTTP structure.

**Comment by simonjbeaumont** [comment]
> This exposes in the client the internal structure of the request (JSON in the body). It would be better to have Swift struct as an abstraction that one hands to the generated code, which is responsible for packaging it and sending it to the server.

To this point, I think that's not quite accurate. There is no need to deal with any seeialization when using the generated client or server, be that JSON or otherwise. 

The server author provides a type that conforms to a Swift protocol that has method requirements determined entirely by Swift input and output types. 

The `.json` here is an enum case of the request type. We have enum cases for each of the document request and response content types. As a server you will need to handle any of the document request types, which your Vapor server does not show, and we structure the generated code with API evolution in mind. Specifically, if an API grows the ability to accept another request content type (perfectly backwards compatible from a HTTP API perspective), the enum just grows another case. The server code will need to handle this to be a compliant server. And, ofc, there's a symmetric discussion to be had about the use of enum values for the response types in the generated client code. 

Hope that helps motivate the shape of the generated code a little more.

**Comment by JetForMe** [comment]
I guess I really don't understand. I wasn't proposing removing any of the existing generated code. But what I see with the way things are right now is I express a request/response in the YAML file, and then I express it again in my Swift code. I want the code that sits between my Swift code and the server to abstract all of that detail away.

Vapor does this for me, in a much more readable (and writeable) fashion. I ask for a Swift type representing the provided data, and it handles unmashaling it. It also validates and throws exceptions that get translated into a response to the client.

I really struggle to see the benefit of the generator for me as the server developer (its benefits for documentation are a bit more evident, but I could probably get that from a tool encountered that generates the YAML from my Vapor code).

**Comment by czechboy0** [comment]
> I express a request/response in the YAML file, and then I express it again in my Swift code

Not exactly, you _document_ your request/response types in the YAML file, and then you _use_ those generated types in your Swift code.

> I ask for a Swift type representing the provided data, and it handles unmashaling it. It also validates and throws exceptions that get translated into a response to the client.

That's exactly what the generated code does for you.

> I really struggle to see the benefit of the generator for me as the server developer (its benefits for documentation are a bit more evident, but I could probably get that from a tool encountered that generates the YAML from my Vapor code).

Have you had a chance to watch the server section of the WWDC talk? That might show those benefits more: https://developer.apple.com/wwdc23/10171?time=972

**Comment by simonjbeaumont** [comment]
> I want the code that sits between my Swift code and the server to abstract all of that detail away.
> 
> Vapor does this for me, in a much more readable (and writeable) fashion. I ask for a Swift type representing the provided data, and it handles unmashaling it. It also validates and throws exceptions that get translated into a response to the client.

The generated code goes one step further. In your Vapor example, you're making a function call into Vapor to decode the incoming HTTP request type into a typed domain-specific request type:

```swift
let req = try inReq.content.decode(RegisterAPNRequest.self)
```

You, as the author, had to pick the right type to pass to `decode(_:)` here and I'm curious to know how you'd write this code to generalise over multiple request and response content types, which are used in many HTTP APIs.

By the time control flow hits your generated code all the unmarshaling has already happened. The value of type `Operations.<OperationID>.Input` that is passed to your handler _is_ the decoded Swift type. All the error handling for malformed requests has already taken place for you, behind the scenes, in the generated code.

I'm wondering if you've been tripped up by the `.json` enum case, which made you think that the decoding hadn't happened yet?

All this being said, we genuinely appreciate feedback on how to make the APIs more expressive and have made changes based on user feedback in the past. If you have any ideas on how we can retain the expressivity of the OpenAPI specification but make things more usable for either client or server adopters, we'd be open to discussing them in detail.

**Comment by JetForMe** [comment]
> You, as the author, had to pick the right type to pass to `decode(_:)` here and I'm curious to know how you'd write this code to generalise over multiple request and response content types, which are used in many HTTP APIs.

I am really only concerned here with writing new APIs, and I have done quite a few. I have never written them to accept more than one type of request. That is, for any given endpoint, it only ever accepts one type of request (e.g. a GET request might have request parameters or path components, a POST or PUT will have JSON or binary data). The only response I can think of that might return different types would be, say, something returning an image, which might be PNG or JPEG, but that can almost be ignored at the REST specification level.

My actual code that handles a request knows that it needs some data and it knows it needs to produce some data. I don't want it to have to care *how* it got the data (e.g. that it was JSON-encoded or whatever). Can't quite do that on requests that might have some data embedded in the request path and some in query parameters, but it’s otherwise pretty close.

The API produced by this generator exposes all of that, *and* it adds additional layers of hierarchy that require a sprinkling of `.init`, which I generally dislike because it makes it a lot harder to understand what is going on when reading the code (unless you're already quite familiar with it).

Alas, I've decided to abandon using the API generator for now. I may in the future find a way to auto-generate the specification file from my code, but I don't foresee using the generated code in my server or client.

**Comment by czechboy0** [comment]
Understood - is there anything else we can help with? If not, please close the issue.

**Comment by simonjbeaumont** [comment]
It sounds like this tool isn’t the right fit for your needs. It’s designed to support the full expressivity of OpenAPI, which caters to a wider range of API semantics than you require for your API server.

As such, the generated API has to account for this. For example, we separate the different parameter locations into their own namespaces to avoid conflicts. There are also plenty of HTTP APIs that respect the Accept HTTP header field in the request, and use it to determine the content type of the response.

**Comment by JetForMe** [comment]
Again, I'm not saying you have to remove that expressivity. I'm saying it should generate additional code so that I'm not forced to use it. The whole point of a code generator is to relieve me of the burden of minutiae and boilerplate. I can work in app-specific data structures, and the framework handles translating that for clients.

But you're right. As-is, this tool does not meet my needs.

**Comment by simonjbeaumont** [comment]
To be clear, we’re genuinely open to additive changes if they can be expressed in a way that generalises well. 

Maybe you could suggest an example `extension` that you think would solve the ergonomic issues you’re having. If it’s generalisable, we could consider generating it.

**Comment by czechboy0** [comment]
Closing for now, @JetForMe if you come up with examples of extensions you'd like to see, please reopen the issue.
