### ISSUE TITLE
Equatable conformance

### ISSUE THREAD

**Issue by cpd** [apple/swift-openapi-generator#546]
### Question

Hi, it's possible to add Equatable conformance to generated models? Adding it post factum prevents automatic synthesis

`Extension outside of file declaring struct 'categoryListPayloadPayload' prevents automatic synthesis of '==' for protocol 'Equatable'`

**Comment by czechboy0** [comment]
Hi @cpd,

all the generated types should already be Equatable (because they're Hashable, which implies Equatable as well). Are you seeing some types _not_ being Equatable?
