### ISSUE TITLE
Generated enums should conform to `CaseIterable`

### ISSUE THREAD

**Issue by rpecka** [apple/swift-openapi-generator#548]
### Motivation

I would like to implement a dropdown picker in my app which lets users select one of the possible enum values to send to an API. I'm able to do this by conforming the enum to `CaseIterable` myself in an extension, but if I do that, I have to implement `allCases` myself which kind of defeats the purpose. I would like the declaration of the enum to have the `CaseIterable` conformance so that `allCases` is synthesized automatically.

### Proposed solution

Add `CaseIterable` conformance synthesized enum declarations.

**Comment by simonjbeaumont** [comment]
This seems totally reasonable.

**Comment by czechboy0** [comment]
Agreed, we'd welcome a PR adding this to both string-based and int-based enums. I don't think it'll be possible for oneOf's, since they have associated values.

**Comment by czechboy0** [comment]
@rpecka have you started working on this or can @PARAIPAN9 pick it up?

**Comment by rpecka** [comment]
I haven't started -- fine if someone else does.

**Comment by czechboy0** [comment]
Ok go ahead, @PARAIPAN9

**Comment by czechboy0** [comment]
This already landed in main, will be in the next release.

**Comment by samdogg7** [comment]
Thank you, I was about to open this as an issue!

**Comment by czechboy0** [comment]
Fixed and released in 1.3.0: https://github.com/apple/swift-openapi-generator/releases/tag/1.3.0
