### ISSUE TITLE
When a delete path do not have responses content an error generated

### ISSUE THREAD

**Issue by ramunasjurgilas** [apple/swift-openapi-generator#572]
### Description

When responses are empty for delete path swift-openapi-generator throws an error:
```
.../openapi.json:1:1 Expected `responses` value for the **DELETE** endpoint under `/me/live_events` to be parsable as Mapping but it was not.LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted
```

When adding response it is not failing any more:

        // ...
                "responses": {
                    "204": {
                        "description": "No content, indicating successful deletion."
                    },
                    "400": {
                        "description": "Bad request, the request was unacceptable, often due to missing a required parameter."
                    },
                    "404": {
                        "description": "Not Found, the resource to be deleted does not exist."
                    },
                    "403": {
                        "description": "Forbidden, the user does not have the necessary permissions for the operation."
                    }
                },
          // ...

### Reproduction

```
        "/live_events": {
            "delete": {
                "summary": "Delete a list of live events",
                "description": "This method deletes multiple events belonging to the authenticated user.",
                "operationId": "delete_live_events_alt1",
                "tags": [
                    "Live\\Essentials"
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/vnd.vimeo.live.event.recurring+json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "password": {
                                        "description": "The user’s password.",
                                        "example": "hunter1",
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "password"
                                ]
                            }
                        }
                    }
                },
                "responses": [],
                "security": [
                    {
                        "oauth2": [
                            "delete"
                        ]
                    }
                ],
                "x-mill-path-aliased": true,
                "x-mill-path-template": "/live_events",
                "x-mill-vendor-tags": [
                    "capability:CAPABILITY_RECURRING_LIVE_EVENTS"
                ]
            }
    }
```

### Package version(s)

Fetching https://github.com/apple/swift-openapi-urlsession from cache
Fetching https://github.com/apple/swift-openapi-generator from cache
Fetching https://github.com/apple/swift-openapi-runtime from cache
Fetched https://github.com/apple/swift-openapi-urlsession from cache (1.30s)
Fetched https://github.com/apple/swift-openapi-runtime from cache (1.38s)
Fetched https://github.com/apple/swift-openapi-generator from cache (1.47s)
Computing version for https://github.com/apple/swift-openapi-urlsession
Computed https://github.com/apple/swift-openapi-urlsession at 1.0.1 (0.57s)
Fetching https://github.com/apple/swift-collections from cache
Fetching https://github.com/apple/swift-http-types from cache
Fetched https://github.com/apple/swift-http-types from cache (0.79s)
Fetched https://github.com/apple/swift-collections from cache (0.95s)
Computing version for https://github.com/apple/swift-openapi-generator
Computed https://github.com/apple/swift-openapi-generator at 1.2.1 (0.45s)
Fetching https://github.com/apple/swift-argument-parser from cache
Fetching https://github.com/apple/swift-algorithms from cache
Fetching https://github.com/jpsim/Yams from cache
Fetching https://github.com/mattpolzin/OpenAPIKit from cache
Fetched https://github.com/apple/swift-algorithms from cache (1.62s)
Fetched https://github.com/apple/swift-argument-parser from cache (1.67s)
Fetched https://github.com/jpsim/Yams from cache (1.68s)
Fetched https://github.com/mattpolzin/OpenAPIKit from cache (1.75s)
Computing version for https://github.com/apple/swift-algorithms
Computed https://github.com/apple/swift-algorithms at 1.2.0 (0.44s)
Fetching https://github.com/apple/swift-numerics.git from cache
Fetched https://github.com/apple/swift-numerics.git from cache (0.68s)
Computing version for https://github.com/apple/swift-argument-parser
Computed https://github.com/apple/swift-argument-parser at 1.3.1 (0.36s)
Computing version for https://github.com/mattpolzin/OpenAPIKit
Computed https://github.com/mattpolzin/OpenAPIKit at 3.1.3 (0.44s)
Computing version for https://github.com/apple/swift-numerics.git
Computed https://github.com/apple/swift-numerics.git at 1.0.2 (0.44s)
Computing version for https://github.com/apple/swift-http-types
Computed https://github.com/apple/swift-http-types at 1.0.3 (0.42s)
Computing version for https://github.com/apple/swift-openapi-runtime
Computed https://github.com/apple/swift-openapi-runtime at 1.4.0 (0.35s)
Computing version for https://github.com/apple/swift-collections
Computed https://github.com/apple/swift-collections at 1.1.0 (0.51s)
Computing version for https://github.com/jpsim/Yams
Computed https://github.com/jpsim/Yams at 5.1.2 (0.44s)
Creating working copy for https://github.com/apple/swift-http-types
Working copy of https://github.com/apple/swift-http-types resolved at 1.0.3
Creating working copy for https://github.com/apple/swift-numerics.git
Working copy of https://github.com/apple/swift-numerics.git resolved at 1.0.2
Creating working copy for https://github.com/apple/swift-openapi-generator
Working copy of https://github.com/apple/swift-openapi-generator resolved at 1.2.1
Creating working copy for https://github.com/mattpolzin/OpenAPIKit
Working copy of https://github.com/mattpolzin/OpenAPIKit resolved at 3.1.3
Creating working copy for https://github.com/apple/swift-argument-parser
Working copy of https://github.com/apple/swift-argument-parser resolved at 1.3.1
Creating working copy for https://github.com/apple/swift-collections
Working copy of https://github.com/apple/swift-collections resolved at 1.1.0
Creating working copy for https://github.com/apple/swift-openapi-runtime
Working copy of https://github.com/apple/swift-openapi-runtime resolved at 1.4.0
Creating working copy for https://github.com/apple/swift-openapi-urlsession
Working copy of https://github.com/apple/swift-openapi-urlsession resolved at 1.0.1
Creating working copy for https://github.com/apple/swift-algorithms
Working copy of https://github.com/apple/swift-algorithms resolved at 1.2.0
Creating working copy for https://github.com/jpsim/Yams
Working copy of https://github.com/jpsim/Yams resolved at 5.1.2
.
├── swift-openapi-generator<https://github.com/apple/swift-openapi-generator@1.2.1>
│   ├── swift-algorithms<https://github.com/apple/swift-algorithms@1.2.0>
│   │   └── swift-numerics<https://github.com/apple/swift-numerics.git@1.0.2>
│   ├── openapikit<https://github.com/mattpolzin/OpenAPIKit@3.1.3>
│   │   └── yams<https://github.com/jpsim/Yams@5.1.2>
│   ├── yams<https://github.com/jpsim/Yams@5.1.2>
│   └── swift-argument-parser<https://github.com/apple/swift-argument-parser@1.3.1>
├── swift-openapi-runtime<https://github.com/apple/swift-openapi-runtime@1.4.0>
│   └── swift-http-types<https://github.com/apple/swift-http-types@1.0.3>
└── swift-openapi-urlsession<https://github.com/apple/swift-openapi-urlsession@1.0.1>
    ├── swift-openapi-runtime<https://github.com/apple/swift-openapi-runtime@1.4.0>
    │   └── swift-http-types<https://github.com/apple/swift-http-types@1.0.3>
    ├── swift-http-types<https://github.com/apple/swift-http-types@1.0.3>
    └── swift-collections<https://github.com/apple/swift-collections@1.1.0>

### Expected behavior

When response is not is not provided source code should be generated.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by czechboy0** [comment]
Hi @ramunasjurgilas,

yes, that's expected. All OpenAPI operations must have at least one response defined.

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#responses-object

**Comment by ramunasjurgilas** [comment]
Thanks @czechboy0 for the info.
