### ISSUE TITLE
Add ability to attach protocols to generated models

### ISSUE THREAD

**Issue by armintelker** [apple/swift-openapi-generator#573]
### Motivation

We need all of our models generated by `swift-openapi-generator` to comply with protocols like `Equatable`or `Identifiable` to work with our overlaying architecture. Manually extending each generated model to conform to these protocols is insufficient and cumbersome, especially as the number of models increases.

### Proposed solution

Add a feature to the `swift-openapi-generator` that allows specifying which protocols the generated models should conform to.  This could be implemented as a configuration option in the generator, enabling automated protocol conformance during the model generation process.

### Alternatives considered

The current workaround is manually extending each generated model, like so:
```swift
extension ModelA: Equatable {}
extension ModelB: Equatable {}
extension ModelC: Equatable {}
extension ModelD: Equatable, Identifyable {
    var id: Int 
    //...
}
```
However, this approach is not scalable and becomes unwieldy as the number of models grows.

### Additional information

If there is already an existing feature to achieve this, i apologize for the oversight and kindly request guidance to the relevant documentation. I could not find any reference to such a feature in the current documentation.

References:

[Identifiable Documentation](https://developer.apple.com/documentation/swift/identifiable)
[Equatable Documentation](https://developer.apple.com/documentation/swift/equatable)
Thank you for considering this request.

**Comment by armintelker** [comment]
Hey, thanks for the quick response. 
I have overseen that the DTO is already conforming to Hashable. This makes, of course, everything a lot easier. So my request gets kind of needless.
Indeed the `Identifiable` protocol suggestion would be more like a "nice to have". 
I could imagine that the generator could add the `Identifiable` to the model as soon it sees a property `id` exists that also conforms to the [constraint](https://developer.apple.com/documentation/swift/identifiable/id-swift.associatedtype) of the protocol.

**Comment by simonjbeaumont** [comment]
This is similar to #383, where could conceivably attach arbitrary conformances or macros that are stated in the config file and it be up to the adopter to ensure these are available in their project. 

It wouldn't be too different from the ability we have know to express `additionalImports`.

**Comment by czechboy0** [comment]
That's true, @simonjbeaumont, and the macro itself would contain the logic for how to e.g. implement `Identifiable`, instead of the generator having to know how to do it. I like that.

**Comment by shadone** [comment]
+1 to this. In my use case it would also be useful to have ability to add Identifiable conformance to some types. There is literally no other way to do this - I have a library that uses swift-openapi-generator to generate the type and expose them publicly.

It would be nice if Swift allowed to add public conformance to a protocol in an extension:
```swift
public extension Components.Schemas.SortType: Identifiable { // compiler error: 'public' modifier cannot be used with extensions that declare protocol conformances
    public var id: String { rawValue }
}
```
Unfortunately this is not possible in Swift, so the only solution I can see is to solve it in the openapi generator.

**Comment by czechboy0** [comment]
Hi @shadone,

does this work?

```

extension Components.Schemas.SortType: Identifiable { // compiler error: 'public' modifier cannot be used with extensions that declare protocol conformances
    public var id: String { rawValue }
}
```

(without the public modifier on the extension, only on the id property).

**Comment by shadone** [comment]
@czechboy0 yes, that works, sorry I forgot to mention this solution in my post. However this "hack" would be needed in every module that imports my library. Additionally it triggers a warning in Xcode 16 / Swift 6
> Extension declares a conformance of imported type 'CommentSortType' to imported protocol 'Identifiable'; this will not behave correctly if the owners of 'LemmyKit' introduce this conformance in the future

Which can be silenced by adding "retroactive" flag

```swift
extension Components.Schemas.SortType: @retroactive Identifiable {
    public var id: String { rawValue }
}
```

This solution feels more like a hack to me, I think the only proper solution is to allow adding custom protocol in the generator itself

**Comment by czechboy0** [comment]
> does the SortType publicly conform to the protocol here or just the "shape" of the protocol

I believe the visibility of the conformance is always derived from the visibility of the extended type and the protocol, i.e. there is no way to privately conform a public type to a public protocol.

But to get more details, starting a thread on the Swift Forums might be a good next step, if you're interested in the lower level compiler details.
