### ISSUE TITLE
Make the generator usable on very big specs

### ISSUE THREAD

**Issue by Frizlab** [apple/swift-openapi-generator#575]
### Motivation

When trying to use the generator for very big OpenAPI specs (e.g. [Stripe’s](https://github.com/stripe/openapi/blob/master/openapi/spec3.yaml)), we get a generated file which takes around 10 minutes to compile on an M3 Max and whose compilation takes more than 10 GB of RAM.

Dealing with that sort of file is challenging and I think the generator should do a better job and generate things differently in order for the compilation to be done in a reasonable time.

### Proposed solution

My understanding is the generator generates a single file which contains everything.

I _think_ splitting the generation in multiple smaller files would help the compiler in dealing with huge OpenAPI specs. I have not tested that theory though.

### Alternatives considered

I believe a possible alternative for clients of big OpenAPI specs would be pre-compile the dedicated client module and depend on the precompiled version of the module instead of the module directly.

Even if this works, it is highly inconvenient, especially if the client is destined to be multiplatform.

**Comment by czechboy0** [comment]
Hi @Frizlab,

have you tried [document filtering](https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.1/documentation/swift-openapi-generator/configuring-the-generator#Document-filtering)? That's the feature designed to address this problem, as we recommend that adopters who generate clients *only* generate the operations they use. That makes your compilation time grow not with the number of operations in the document, but with the number of operations you're calling.

**Comment by Frizlab** [comment]
Thanks, no I have not tested filtering.

The end goal is definitely to give access to all of the OpenAPI specs through a convenient package. Maybe using filtering and splitting the module in multiple modules I could achieve my goal.

I’m gonna close this issue for now and reopen if filtering goes to a dead-end!

**Comment by simonjbeaumont** [comment]
@Frizlab we have some numbers showing that splitting would indeed improve things: https://github.com/apple/swift-openapi-generator/issues/253
