### ISSUE TITLE
visionOS can't use

### ISSUE THREAD

**Issue by koi646** [apple/swift-openapi-generator#577]
### Description

When I was using it in the visionOS project, I encountered an error
![image](https://github.com/apple/swift-openapi-generator/assets/7830825/aafefb72-8952-4c5a-afb7-65d88049d1a3)
![image](https://github.com/apple/swift-openapi-generator/assets/7830825/c18a82a4-816c-4538-a91e-0391e110c80b)

I found that there is no check for the visionOS platform in Yams, which causes the code to execute go "else"

### Reproduction

openapi: 3.0.0
paths:
  /health:
    get:
      operationId: AppController_health
      parameters: []
      responses:
        '200':
          description: ''

### Package version(s)

1.2.1

### Expected behavior

well

### Environment

xcode 16-beta
swift 6.0

**Comment by koi646** [comment]
target visionOS 1.1

**Comment by simonjbeaumont** [comment]
Thanks @koi646, looks like Yams needs to either extend their `if os(...) || os(...) || ...` dance or instead replace with a `#if canImport(Darwin)`.

**Comment by simonjbeaumont** [comment]
OK @koi646 I think you are trying to link `_OpenAPIGeneratorCore` in your visionOS app target, which will not work.

I have tested that I can build the `HelloWorldiOSClientApp` example project in this repo with the latest Xcode Beta for visionOS (changing only the "Base SDK" setting from iOS to visionOS).

To confirm this was the issue, I also added `_OpenAPIGeneratorCore` to the "Link Binary With Libraries" and reproduced a build failure at the same point in Yams.

This is an unfortunate and subtle trip hazard: when you add a package plugin to an Xcode project, it offers which of the library products from the package you'd like to link in your application and defaults to select `_OpenAPIGeneratorCore`. This library is only used by the generator itself.

In addition to trying to document this as best we can, we have some compiler guards in the `_OpenAPIGeneratorCore` that I thought would fire to point you in the right direction:

```swift
#if !(os(macOS) || os(Linux))
#error(
    "_OpenAPIGeneratorCore is only to be used by swift-openapi-generator itself—your target should not link this library or the command line tool directly."
)
#endif
```

Please try auditing your app target for this erroneous link dependency and we'll take a look and see if we can firm up the above compiler hint.

**Comment by koi646** [comment]
You are right, my friend. I made a foolish mistake. After unlinking swift-openapi-generator, the program compiled successfully. It is not a runtime package, but I misunderstood it at first.
