### ISSUE TITLE
How to convert the binary obtained from the server into a playable Data type?

### ISSUE THREAD

**Issue by koi646** [apple/swift-openapi-generator#578]
### Question

When I use URLSession, there are many examples，butI looked at the official example,  didn't find how to convert the binary downloaded from the server into a data structure that can be used by AudioPlayer.
![image](https://github.com/apple/swift-openapi-generator/assets/7830825/2f50f57d-1e62-4656-917b-667041a21923)
![image](https://github.com/apple/swift-openapi-generator/assets/7830825/eaf70483-7769-45d6-8889-1349064e2bb6)
When I printed out audio_mpeg, I found that it is of type OpenAPIRuntime.HTTPBody.
How can I convert OpenAPIRuntime.HTTPBody type to be used by AudioPlayer?

**Comment by czechboy0** [comment]
Hi @koi646,

you turn an `HTTPBody` (a stream of byte chunks) into `Data` by accumulating it using this initializer: https://swiftpackageindex.com/apple/swift-openapi-runtime/1.4.0/documentation/openapiruntime/foundation/data/init(collecting:upto:)

So something like:

```swift
let audioData = Data(collecting: audio_mpeg, max: 10 * 1024 * 1024) // chose max of 10MB, adjust as needed
```

From this point on, converting the Data value to something compatible with AudioPlayer, the story is the same as when using URLSession directly. So for example: https://developer.apple.com/documentation/avfaudio/avaudioplayer/1388809-init

**Comment by koi646** [comment]
thx,  I will give it a try.

**Comment by czechboy0** [comment]
Closing for now, please reopen if the suggested solution still didn't fix your issue.
