### ISSUE TITLE
HTTPTypes linker error if multiple targets use open API generator

### ISSUE THREAD

**Issue by smoser90** [apple/swift-openapi-generator#579]
### Question

Hi,

I'm currently facing an issue if I want to build my project that contains two targets, which both are using open API generator. I always get HTTPType linker errors. If I remove one of those two targets from my project everything works as intended. 

Each target has its own openapi-generator-config.yaml and openapi.yaml and both targets are used in the main project in different locations via import "TargetName"

Is there anything specific to be aware of if I want to use multiple targets? 

Thanks in advance.

brg
<img width="617" alt="Screenshot 2024-06-25 at 15 52 11" src="https://github.com/apple/swift-openapi-generator/assets/173811145/969b76f3-0375-4879-99e3-6f90089612a9">

**Comment by Jon889** [comment]
Why is this required?
