### ISSUE TITLE
Tutorial doc text color issue on light theme

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-openapi-generator#582]
### Description

<img width="1624" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/43724855/9f03e239-5231-4885-b7b3-1958684d21ee">

<img width="1624" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/43724855/d32a70e6-bce3-4426-9fb5-c2fc81faa04a">

### Additional information

Link: https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.1/tutorials/swift-openapi-generator/clientxcode

Open the issue for a record. I'll take a look at this issue later this week.

**Comment by czechboy0** [comment]
Hi @Kyle-Ye - thanks for opening an issue, although I suspect it'll eventually land either on swift-docc or the Swift Package Index. As the authors of only the markdown files, I don't think we have any control over the styling.

**Comment by czechboy0** [comment]
Closing this, as this isn't controlled by the author of the docc catalog, but by the docc tooling itself. @Kyle-Ye - please file this on https://github.com/swiftlang/swift-docc and link it from here? Thanks

**Comment by Kyle-Ye** [comment]
Looks like to a mis config of theme.json(default value in docc-render or SPI's custom injected one).

Any way, this is confirm to be fixed on 1.4.0 version documentation hosted on SPI.

https://swiftpackageindex.com/apple/swift-openapi-generator/1.4.0/tutorials/swift-openapi-generator/clientxcode
