### ISSUE TITLE
Check for updated spec before generating

### ISSUE THREAD

**Issue by OurBigAdventure** [apple/swift-openapi-generator#584]
### Motivation

For a large API spec, generating the code can take a long time.  Each time a build happens the code gets re-generated and that makes development and testing a slow process.

### Proposed solution

It seems simple enough to check the modified date of the spec file (or config file) and if it is older than the date of the generated code file(s) then skip the generator because the spec hasn't changed.

This way the generator only runs if:

- the spec or config has changed
- the generated code doesn't exist

### Alternatives considered

Disable the plugin for development and try to remember to re-enable it for any release builds.

**Comment by czechboy0** [comment]
Hi @OurBigAdventure,

this is how build plugins, and thus Swift OpenAPI Generator's build plugin, already works today. If you're seeing reruns of the generator when none of its inputs have changed, can you provide more diagnostics or repro steps? Thanks

**Comment by OurBigAdventure** [comment]
Just tested in my updated project and it appears that is the case.  The issue was coming from that old project where I had the strange errors, I'm just going to finish the migration from that project and ignore the strange behaviors.

Thanks for the quick reply!
