### ISSUE TITLE
Support multiple response body content types

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#6]
Support multiple response body content types.

This is about generating all the supported content types.

The Accept header propagation is now broken out into #160.

**Comment by czechboy0** [comment]
Added the `design` label, as this task will require a proposal, as it introduces a new paradigm - the Accept header hinting at the expected response Content-Type, where there isn't a single obvious solution, so should be discussed first.

**Comment by czechboy0** [comment]
It's also possible we could split this into two issues:
- supporting multiple response body content types
- providing the Accept header to the server to help it make a decision about which response content type to use

**Comment by simonjbeaumont** [comment]
> providing the Accept header to the server to help it make a decision about which response content type to use

IMO this has to be part of the solution as it's the conventional way of telling the server what you want when it can provide different response types.

**Comment by czechboy0** [comment]
For sure, was just trying to break out the work that's non-controversial (supporting multiple content types) from the thing that needs design (how we provide the value for the Accept header to the adopter on the server). Not saying we would make a release with a partial implementation, just that these things can land in separate PRs, for easier review.

**Comment by czechboy0** [comment]
Now released in 0.1.7 under the `multipleContentTypes` feature flag.
