### ISSUE TITLE
The output formatting of JSON encoding/decoding should be more configurable

### ISSUE THREAD

**Issue by jakepetroules** [apple/swift-openapi-generator#605]
### Motivation

I never ever want to emit JSON without the `.withoutEscapingSlashes` option, since it drastically reduces readability in JSON payloads where file paths are prevalent.

### Proposed solution

Please consider making `Converter.encoder` public or providing an option to pass in an array of `outputFormatting` flags.

**Comment by czechboy0** [comment]
Fixed in https://github.com/apple/swift-openapi-runtime/pull/112
