### ISSUE TITLE
Error during build: Injecting stub binary into codeless framework

### ISSUE THREAD

**Issue by SergioB-dev** [apple/swift-openapi-generator#612]
### Description

I just installed this package and ran it successfully, along with `swift-openapi-runtime` and `swift-openapi-urlsession`. Everything builds fine locally. Then when I try to build it in the cloud, I got an error (something about `OpenAPIGenerator` not being enabled), so I added a script in `ci_scripts/ci_post_clone.sh` to get past that. Now I'm getting a new error that I don't know how to fix.

### Reproduction

 ci_post_clone.sh
```console
#!/bin/sh

defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

```

Error log
```
PhaseScriptExecution Running\ swift-openapi-generator /Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArabicCompanion.build/Debug-iphoneos/ArabicCompanion.build/Script-721AB31E2C693F620084DD68.sh (in target 'ArabicCompanion' from project 'ArabicCompanion')
    cd /Volumes/workspace/repository
    /bin/sh -c /Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArabicCompanion.build/Debug-iphoneos/ArabicCompanion.build/Script-721AB31E2C693F620084DD68.sh

/Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArabicCompanion.build/Debug-iphoneos/ArabicCompanion.build/Script-721AB31E2C693F620084DD68.sh: line 20:  9636 Segmentation fault: 11  /usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow mach-lookup (global-name \"com.apple.lsd.mapdb\"))
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/yw/fzbppkzd3vb78z9q3q3kt9f80000gn/T\")
)
(deny file-write*
    (subpath \"/Volumes/workspace/repository\")
)
(allow file-write*
    (subpath \"/Volumes/workspace/DerivedData/SourcePackages/plugins/ArabicCompanion.output/ArabicCompanion/OpenAPIGenerator\")
    (subpath \"/Volumes/workspace/.TemporaryItems/folders.501/TemporaryItems\")
    (subpath \"/Volumes/workspace/.TemporaryItems/folders.501/TemporaryItems/NSIRD_xcodebuild_o98spP\")
)
" "/${BUILD_DIR}/${CONFIGURATION}/swift-openapi-generator" generate /Volumes/workspace/repository/ArabicCompanion/openapi.yaml --config /Volumes/workspace/repository/ArabicCompanion/openapi-generator-config.yaml --output-directory /Volumes/workspace/DerivedData/SourcePackages/plugins/ArabicCompanion.output/ArabicCompanion/OpenAPIGenerator/GeneratedSources --plugin-source build
Command PhaseScriptExecution failed with a nonzero exit code
```

### Package version(s)

```console
swift-openapi-generator 1.3.0
siwft-openapi-runtime 1.5.0
swift-openapi-urlsession 1.0.2
```

### Expected behavior

To successfully build this project in the cloud.

### Environment

```swift
Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-darwin24.0.0
```

### Additional information

full log:
[xcodebuild-build.log](https://github.com/user-attachments/files/16575822/xcodebuild-build.log)

**Comment by czechboy0** [comment]
Hi @SergioB-dev,

I believe you're hitting the same Xcode + macOS seed incompatibility, please upgrade both to the same latest seed, more in: https://github.com/apple/swift-openapi-generator/issues/610#issuecomment-2273405960

**Comment by SergioB-dev** [comment]
@czechboy0 I've already updated my OS to match the latest Xcode

```console
Mac Version 15.0 Beta (24A5309e)
Xcode Version 16.0 beta 5 (16A5221g)
```

I've already gotten past the compile error mentioned in #610 and have been running the project successfully. As I stated in the original post, this compiles fine locally but the error that's listed is coming from Xcode cloud.

**Comment by czechboy0** [comment]
Ok glad that's working. You'll need to wait until Xcode Cloud supports the latest seeds and then switch your workflows to use them. We don't have any ability to help with that here though.

**Comment by SergioB-dev** [comment]
I figured that, thanks for confirming.
