### ISSUE TITLE
Optimising build time

### ISSUE THREAD

**Issue by niklassaers** [apple/swift-openapi-generator#613]
### Question

Hi,
in my app I have two different OpenAPI schemas I need to use, so I've made a framework for each, ContentAPI and TheMiddleware (great names). This works fairly well, but I'm having issues around build times:

![BuildTime](https://github.com/user-attachments/assets/dff170ea-a902-4fb9-b787-10c037306c4a)

The ContentAPI generator step will run for 0,6s and output a Types.swift that takes 5,9s to compile, and spend 32s to verify the framework. TheMiddleware is in a worse state because it contains too much from a source where I have less control, and it takes 2,7s to generate, then 30,6s for Types.swift to compile and 32,3s to "Verify Modularization".

Any suggestions to how to improve the build times for my project?

For instance, I'd expect that by splitting up Types.swift into multiple files for the different parts, the compilation could be more parallelised. This is me just assuming, though, as I honestly don't know how the compilers deals with Types.swift under the hood.

I haven't figured out what the Verify Modularization step is about and how that relates to the generated input files. Any ideas?

**Comment by czechboy0** [comment]
Yes you can likely get a noticeable performance improvement by using filtering and generate subsets of your operations into separate modules. Previous discussions: https://github.com/apple/swift-openapi-generator/issues/253

**Comment by niklassaers** [comment]
Should anywhere land here via a search engine looking for "Verify Modularization of", this comes because ENABLE_MODULE_VERIFIER "Enable Module Verifier" is enabled by default when you create a new framework. I haven't found much to understand what this actually does for me, but my impression is that this is mainly intended for frameworks that interact with C or C++ code and helps that code be able to be used in import statements in Swift (or @import in ObjC). Since my frameworks are all Swift from swift-openapi-generator, I've turned this option off and am saving the build time. Curious to see what unintended consequences will come of this ;-)

**Comment by simonjbeaumont** [comment]
> Since my frameworks are all Swift from swift-openapi-generator, I've turned this option off and am saving the build time.

@niklassaers thank you for sharing this tip. I'm not an expert on this option but I guess if folks aren't planning on vending a framework outside their project it might be a useful tip for others. Presumably this setting can be toggled on a framework-by-framework basis (not just at the project level).

> ... very interesting analysis on one big file vs smaller ones :-) Looking forward to following that.

Would you mind giving us the `wc -l` of your generated files, before and after filtering? 

We hadn't prioritised splitting the generated files further but it's always nice to have concrete data to back that up. Maybe you could respond on _that_ issue with these findings, if you have time?
