### ISSUE TITLE
Allow adding middleware after Client has been initialized

### ISSUE THREAD

**Issue by marianheinsen** [apple/swift-openapi-generator#680]
### Motivation

I'm developing a middleware for the OpenAPI Client which intercepts unauthorized requests and tries to automatically refresh authentication when stored credentials are available (e.g. username / password or refresh token). For the refresh, another API call has to be made from within the middleware's handler.

 ```swift
package struct RefreshMiddleware: ClientMiddleware {
    let provider: any AuthenticationProvider
    
    package func intercept(
        _ request: HTTPRequest,
        body: HTTPBody?,
        baseURL: URL,
        operationID: String,
        next: (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
    ) async throws -> (HTTPResponse, HTTPBody?) {
        let (response, responseBody) = try await next(request, body, baseURL)
        
        if response.status.code == 401 {
            if let credentials = provider.retrieveCredentials() {
                // Can't access the client here to refresh authentication
            }
        }
        
        return (response, responseBody)
    }
}
```

 At the moment, it's not possible to use the Client itself in a clean way for this request. As the Client is not accessible from within the middleware, I need to pass a closure into the middleware which handles the refresh from the outside:

```swift
let refreshAuthentication: @Sendable (String) -> Void

// ...

if response.status.code == 401 {
    if let credentials = provider.retrieveCredentials() {
        refreshAuthentication(credentials)
    }
}
```

This is still not a great solution because the Client instance is inaccessible during initialization of the middleware as it itself is part of the initialization of the Client. So there is a circular dependency:

```swift
let client = Client(
    serverURL: try! Servers.Server1.url(),
    transport: URLSessionTransport(),
    middlewares: [
        RefreshMiddleware(provider: provider, refresh: { credentials in
            // Can't access the client here either
        })
    ]
)
```

### Proposed solution

I have multiple solutions for this in mind, but probably the easiest would be to allow middleware to be added after the Client has been initialized. Something like the following:

```swift
let client = Client(
    serverURL: try! Servers.Server1.url(),
    transport: URLSessionTransport()
)

client.middlewares = [
    RefreshMiddleware(provider: provider, refresh: { credentials in
        // Can access the client here!
    })
]
```

This would also open up other possibilities of customization, generally making the configuration of middlewares more dynamic. I can imagine other use cases where the set of middlewares to apply may not be fully determined during the initialization of the Client.

### Alternatives considered

Other approaches considered:
- using late initialization of the Client to access it from the closure (makes each access to the Client mutating)
- assembling the refresh request "manually" instead of using the Client (defeats the purpose of the OpenAPI Generator)
- handling the auto-refresh mechanism on a higher level and not in middleware (fragments infrastructure logic to multiple layers, makes orchestration with other middleware such as auto-retry harder)

One big catch with my proposed approach is that I'm deliberately introducing a circular dependency between the Client and a middleware. Calling a different endpoint inside of a middleware introduces some complexity which needs to be managed carefully, as the new request itself is obviously subject to the same set of middlewares applied to the Client. If not managed correctly, this can lead to undesired consequences such as infinite loops.

It's obviously the responsibility of the developer to consider and handle this risk (for example by excluding middlewares from some set of endpoints), and I'm not asking you to encourage this approach.

It would help a lot if you considered my feature request. Thanks!

**Comment by czechboy0** [comment]
Hi @marianheinsen,

this is a relatively common pattern, and if you don't want to create the auth request manually, just create two clients - one without the authentication middleware, and one with. And the middleware would use the unauthenticated client.

The generated Client type is a lightweight struct, so you don't need to avoid creating more than one of them.

**Comment by marianheinsen** [comment]
Hi @czechboy0,
Thank you for the fast response. Creating multiple clients is indeed a good solution for my use case. This also moves the middleware-to-route mapping out of the middleware to a higher layer.
