### ISSUE TITLE
Reduce error handling code between different handlers with similar logic

### ISSUE THREAD

**Issue by Dracks** [apple/swift-openapi-generator#687]
### Question

Hello, 

I'm using the openapi-generator with Vapor, and I found that I ended generating a lot of code that is identical, because all the responses, no matter the error, are almost identical. I created a discussion in the forum of swift (here: https://forums.swift.org/t/trying-to-reduce-boilercode/76278/17 ) but seems that there is nothing appart of what I did with some macro, that allow you to reduce a huge bunch of this stuff.

Maybe I'm doing it wrong. There is some more elegant way to reduce this? 

Thanks, 
Jaume.

**Comment by czechboy0** [comment]
Hi @Dracks,

this tool generates code for the OpenAPI document. If the OpenAPI document contains a lot of duplicated types, the generated Swift code will contain duplicated types. There isn't much the tool can do.

Could you post your OpenAPI doc? Maybe there are ways to optimize that

**Comment by czechboy0** [comment]
I see, that makes sense. The timing is fortunate here, we recently landed an [improved error handling](https://swiftpackageindex.com/apple/swift-openapi-generator/1.5.0/documentation/swift-openapi-generator/soar-0011) proposal, which would allow you to write convenience functions that validate your input and throw specific errors that get translated to the appropriate response status codes. So you wouldn't need to repeat as much of the error handling in every handler - it's designed to enable the writing of reusable utility functions, which still result in specific error codes.

Can you give that a try and see if it helps?

**Comment by Dracks** [comment]
your proposal here is to simply throw an error that implements that protocol, and then catch it on the middleware?

**Comment by czechboy0** [comment]
Yup, exactly.

**Comment by Dracks** [comment]
that will means, that if in the open-api, you add any extra field in the error types, this will not be detected. right?

**Comment by czechboy0** [comment]
I meant that you'd hand-write an error type in your project and conform that to the protocol. I didn't mean that you'd use the generated schema as an error type.

**Comment by Dracks** [comment]
Yeah, I get it.

**Comment by czechboy0** [comment]
Okay, closing for now, please reopen if the new error handling features didn't help.
