### ISSUE TITLE
Make request/response bodies an async sequence of bytes

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#9]
For simplicity, initially the type holding the raw request and response body data is `Foundation.Data`, but that prevents use cases where large amounts of data need to be sent/received if the memory limit of the process is low.

What should be possible: a uploading/downloading large (multi-GB) files without buffering them into memory on either client/server ends.

**Comment by FranzBusch** [comment]
This is an important topic to cover and something that we are currently discussing in the broader ecosystem. [The SSWG is currently gathering requirements for a general purpose HTTP server](https://forums.swift.org/t/requirements-for-a-high-level-http-server-type/65337). One of the key functionalities of this new type is support for full bidirectional streaming.
I think we should follow the API design of the general purpose HTTP server here in OpenAPI.

**Comment by czechboy0** [comment]
We might need to provide an async body not just for raw byte content types, but also for text/*, as text/event-stream would need that to work.

Either we'll exclude text/event-stream from being returned as String, or we'll need to provide AsyncSequence<String> for text bodies.
