### ISSUE TITLE
[Question] How to add macros to response objects

### ISSUE THREAD

**Issue by brandonmaul** [apple/swift-openapi-generator#94]
For example, if I have an endpoint specified in the OpenAPI spec that returns a "User" object - how would i go about adding the new `@Model` or `@Observable` macros to that object?

**Comment by denil-ct** [comment]
I'm not sure if this is within the scope of this project, as described [here](https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.3/documentation/swift-openapi-generator/project-scope-and-goals). I don't think the OpenAPI generator should be worried about how the generated code is being used.

If something like this needs to be implemented, we would probably need to incorporate a config file similar to [swift-protobuf](https://github.com/apple/swift-protobuf/blob/main/Sources/protoc-gen-swift/Docs.docc/spm-plugin.md#configuring-the-plugin) for the plugin, describing how to handle each file. 

Thoughts? @czechboy0 , @simonjbeaumont

**Comment by czechboy0** [comment]
Hi @brandonmaul, as @denil-ct touched on, I'd encourage you to read the following two docs, which explain how generated types should be used:
- https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.3/documentation/swift-openapi-generator/api-stability-of-generated-code
- https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.3/documentation/swift-openapi-generator/project-scope-and-goals

The generated types are stateless structs, which are just meant to be a type-safe representation of the HTTP payloads. Most likely, if you need observation and other stateful properties, or adding stored properties, you wouldn't use the generated types directly, but you'd wrap them in your own types, which can add the desired behavior.

A good way to think about this is to treat the generated types like you would any other type that someone provided to you, such as by importing a system framework, or depending on someone else's package. You also wouldn't try to amend those types, but you'd wrap them in your custom, handwritten types. The same rule applies here, the generated types are also types you don't directly own, but are generated for you at compile time.

Hope that makes sense, if that resolves your question, please close the issue; or let us know if you have any follow-up questions 🙂

**Comment by brandonmaul** [comment]
@czechboy0 @denil-ct Yes, thank you both! That makes a lot of sense. I really appreciate the detailed response!
